extensioncard = sgs.Package("jile_card",sgs.Package_CardPack, true)

jl_sdjls = sgs.CreateBasicCard{
	name = "jl_sdjls",
	class_name = "JlSdjls",
	subtype = "jiexusheng_card",
--	target_fixed = true,
    can_recast = false,
	damage_card = true,
	filter = function(self,targets,to_select,source)
	    local slash = CardIsAvailable(source,"slash","jl_sdjls",self:getSuit(),self:getNumber())
		if slash
		then
	    	return source:inMyAttackRange(to_select)
			and source:canSlash(to_select,slash)
	    	and #targets<=sgs.Sanguosha:correctCardTarget(sgs.TargetModSkill_ExtraTarget,source,self)
		end
	end,
	on_effect = function(self,effect)
		local source,target,room = effect.from,effect.to,effect.to:getRoom()
		room:addPlayerMark(source,"drank")
		room:setEmotion(source,"analeptic")
		room:getThread():delay(777)
		room:setPlayerChained(target,true)
		room:getThread():delay(777)
		local Slash = sgs.SlashEffectStruct()
        Slash.from = effect.from
        Slash.nature = sgs.DamageStruct_Thunder
        Slash.slash = effect.card
        Slash.to = effect.to
        Slash.drank = source:getMark("drank")>0 and source:getMark("drank") or effect.card:getTag("drank"):toInt()
        Slash.nullified = effect.nullified
        Slash.no_offset = effect.no_offset
        Slash.no_respond = effect.no_respond
        Slash.multiple = effect.multiple
        local jink_table = sgs.QList2Table(effect.from:getTag("Jink_"..effect.card:toString()):toIntList())
		Slash.jink_num = jink_table[1] or 1
        room:setPlayerMark(source,"drank",0)
		room:slashEffect(Slash)
		room:addPlayerHistory(source,"Slash")
		return false
	end,
    available = function(self,player)
        return CardIsAvailable(player,"slash","jl_sdjls",self:getSuit(),self:getNumber())
    end,
}
jl_sdjls:clone(0,7):setParent(extensioncard)
jl_sdjls:clone(1,7):setParent(extensioncard)


jlCardOnTrigger = sgs.CreateTriggerSkill{
	name = "jlCardOnTrigger",
	events = {sgs.DamageCaused},
	frequency = sgs.Skill_Compulsory,
	global = true,
	can_trigger = function(self,target)
		if table.contains(sgs.Sanguosha:getBanPackages(),"jile_card")
		then return end
		return target:isAlive()
	end,
	on_trigger = function(self,event,player,data,room)
 		if event == sgs.DamageCaused
		then
		    local damage = data:toDamage()
        	if damage.card
			and damage.to:isKongcheng()
			and damage.card:isKindOf("JlSdjls")
        	then
	        	Skill_msg("jl_sdjls",player)
		    	DamageRevises(data,1,player)
			end
		end
		return false
	end,
}

jl_yanlinmaoTrVS = sgs.CreateViewAsSkill{
	name = "jl_yanlinmao",
	n = 2,
	view_filter = function(self,selected,to_select)
       	return not to_select:isEquipped()
	end,
	view_as = function(self,cards)
	   	if #cards<2 then return end
	    local pattern = sgs.Sanguosha:getCurrentCardUsePattern()
       	pattern = sgs.Sanguosha:cloneCard("slash")
	   	pattern:setSkillName("jl_yanlinmao")
	   	for _,cid in sgs.list(cards)do
	   	    pattern:addSubcard(cid)
	   	end
		return pattern
	end,
	enabled_at_response = function(self,player,pattern)
		return string.find(pattern,"slash")
		and player:getHandcardNum()>1
	end,
	enabled_at_play = function(self,player)
		return player:getHandcardNum()>1
		and sgs.Slash_IsAvailable(player)
	end,
}
jl_yanlinmaoTr = sgs.CreateTriggerSkill{
	name = "jl_yanlinmao",
	frequency = sgs.Skill_Compulsory,
	view_as_skill = jl_yanlinmaoTrVS,
	events = {sgs.TargetSpecifying,sgs.ChangeSlash,sgs.DamageCaused,sgs.SlashMissed},
	can_trigger = function(self,target)
		return target:getWeapon()
		and target:getWeapon():isKindOf("JlYanlinmao")
	end,
	on_trigger = function(self,event,player,data,room)
   		if event == sgs.TargetSpecifying
	   	then
	       	local use,can = data:toCardUse(),false
	       	if use.card:isKindOf("Slash") 
	       	then
	           	for _,to in sgs.list(use.to)do
			   		to:addQinggangTag(use.card)
    	           	if to:getArmor() then can = to end
	           	end
				if can
				then
                    room:sendCompulsoryTriggerLog(player,"jl_yanlinmao")
	             	room:setEmotion(player,"weapon/jl_yanlinmao")
				end
	       	end
	       	if use.card:isKindOf("Slash") 
	       	then
	           	for _,to in sgs.list(use.to)do
   	             	if to:getGender() ~= player:getGender()
	         		and room:askForSkillInvoke(player,"jl_yanlinmao",sgs.QVariant("choice1:"..to:objectName()))--double_sword
					and not room:askForDiscard(to,"jl_yanlinmao",1,1,true,false,"@bingyueg:jl_yanlinmao:"..player:objectName())
					then player:drawCards(1,self:objectName()) end
	           	end
	       	end
	       	data:setValue(use)
		elseif event == sgs.ChangeSlash
	   	then
	       	local use = data:toCardUse()
	       	if use.card:isKindOf("Slash")
			and use.card:subcardsLength()>=player:getHandcardNum()
			and use.to:length()>1
			then
	         	room:setEmotion(player,"weapon/jl_yanlinmao")
			end
			local tos = {}
	       	for _,to in sgs.list(use.to)do
    	        table.insert(tos,to:objectName())
	       	end
	       	if use.card:objectName() == "slash"
	       	and room:askForSkillInvoke(player,"jl_yanlinmao",sgs.QVariant("choice2:slash:"..table.concat(tos,"+")),false)--double_sword
	       	then
	        	tos = sgs.Sanguosha:cloneCard("fire_slash")
	        	tos:setSkillName("jl_yanlinmao")
				if use.card:isVirtualCard()
				then tos:addSubcards(use.card:getSubcards())
				else tos:addSubcard(use.card) end
	         	room:setEmotion(player,"weapon/jl_yanlinmao")
				use.card = tos
	       	end
	       	data:setValue(use)
		elseif event == sgs.SlashMissed
		then
			local effect = data:toSlashEffect()
			local dest = effect.to
			local source = effect.from
			source:setTag("SlashMissed",data)
			if effect.jink
			and effect.slash:isKindOf("Slash")
			and room:askForDiscard(source,"jl_yanlinmao",2,2,true,true,"@guanbing:jl_yanlinmao:"..effect.slash:objectName(),"^JlYanlinmao","jl_yanlinmao")
			then
	         	room:setEmotion(source,"weapon/jl_yanlinmao")
                room:slashResult(effect,nil)
			end
			if effect.jink
			and effect.slash:isKindOf("Slash")
			then
				room:askForUseSlashTo(source,dest,"@bingyuegong-slash:"..dest:objectName())
			end
    	elseif event == sgs.DamageCaused
		then
		    local damage = data:toDamage()
        	if damage.card
			and damage.to:isKongcheng()
			and damage.card:isKindOf("Slash")
        	then
	        	room:sendCompulsoryTriggerLog(player,"jl_yanlinmao")
	         	room:setEmotion(player,"weapon/jl_yanlinmao")
		    	DamageRevises(data,1,player)
			end
			damage = data:toDamage()
   	    	local todata = sgs.QVariant()
       		todata:setValue(damage.to)
            local give,dh,oh = {},damage.to:getDefensiveHorse(),damage.to:getOffensiveHorse()
        	if damage.card:isKindOf("Slash")
			and (dh or oh)
	       	and room:askForSkillInvoke(player,"jl_yanlinmao",sgs.QVariant("choice3:"..damage.to:objectName()))--double_sword
        	then
	         	room:setEmotion(player,"weapon/jl_yanlinmao")
	    		if dh then table.insert(give,"DefensiveHorse") end
				if oh then table.insert(give,"OffensiveHorse") end
		     	give = room:askForChoice(player,"jl_yanlinmao",table.concat(give,"+"))
		    	if give == "DefensiveHorse" then room:throwCard(dh,damage.to,player)
				elseif give == "OffensiveHorse" then room:throwCard(oh,damage.to,player) end
			end
			player:setTag("SlashDamage",data)
        	if damage.card:isKindOf("Slash")
			and damage.to:getCardCount()>0
	       	and room:askForSkillInvoke(player,"jl_yanlinmao",sgs.QVariant("choice4:"..damage.to:objectName()))--double_sword
			then
	         	room:setEmotion(player,"weapon/jl_yanlinmao")
 				for i = 1,2 do
       	        	if damage.to:getCardCount()>0
					then
			    		i = room:askForCardChosen(player,damage.to,"he","jl_yanlinmao")
				    	room:throwCard(i,damage.to,player)
					end
				end
				return DamageRevises(data,-damage.damage,player)
			end
		end
		return false
	end
}
jl_yanlinmao = sgs.CreateWeapon{
	name = "jl_yanlinmao",
	class_name = "JlYanlinmao",
	range = 5,
	on_install = function(self,player)
		local room = player:getRoom()
		room:acquireSkill(player,jl_yanlinmaoTr,true,true,false)
		return false
	end,
	on_uninstall = function(self,player)
		local room = player:getRoom()
		room:detachSkillFromPlayer(player,"jl_yanlinmao",true,true)
		return false
	end,
}
jl_yanlinmao:clone(sgs.Card_Club,6):setParent(extensioncard)

local skills = sgs.SkillList()
if not sgs.Sanguosha:getSkill(jlCardOnTrigger:objectName())
then skills:append(jlCardOnTrigger) end
if not sgs.Sanguosha:getSkill(jl_yanlinmaoTrVS:objectName())
then skills:append(jl_yanlinmaoTrVS) end
sgs.Sanguosha:addSkills(skills)

sgs.LoadTranslationTable{
	["jilebao"] = "极乐包",
	["jile_card"] = "Meme",
	["jl_chonger"] = "曹冲儿",
	["#jl_chonger"] = "找妖的神童",
	["jl_renxin2"] = "仁馨",
	[":jl_renxin2"] = "出牌阶段，你可以弃置一张装备牌，然后令一名角色回复1点体力。",
	["jl_chengxiang2"] = "称像",
	[":jl_chengxiang2"] = "当你回复体力时，你可以展示牌堆顶4张牌，然后任意分配这些牌。",
	["jl_sdjls"] = "Tác Đĩnh Tửu Lôi Sát",
	[":jl_sdjls"] = "Bài cơ bản\n\
Thời điểm: Một lần trong giai đoạn hành động\nMục tiêu: 1 người trong tầm đánh\nHiệu quả: Bạn xem như sử dụng [Tửu], mục tiêu tiến vào trạng thái xích, bạn gây 1 sát thương Lôi cho mục tiêu; Nếu mục tiêu không có bài trên tay, sát thương này +1.",
	["jiexusheng_card"] = "Lá thái bảo",
	["jl_weiyan"] = "魏延",
	["designer:jl_weiyan"] = "吃蛋挞的折棒",
	["illustrator:jl_weiyan"] = "吃蛋挞的折棒",
	["#jl_weiyan"] = "剑定为贞",
	["jl_yiyan"] = "义延",
	[":jl_yiyan"] = "游戏开始时，你令一名角色获得“烈弓（标）”。当你造成或受到1点伤害后，你可以升级一次【烈弓】：1、烈弓（界）；2、烈弓（谋）。",
	["jl_yiyan0"] = "义延：请选择令一名角色获得“烈弓（标）”",
	["jl_yiyan1"] = "义延：你可以升级一次【烈弓】",
	["jl_dingzhen"] = "鼎阵",
	[":jl_dingzhen"] = "当一名武将牌上有“烈弓”的角色使用【杀】造成伤害时，你可以选择一项：1、令其摸一张牌；2、此【杀】不计入次数限制。背水：你失去1点体力。",
	["jl_dingzhen1"] = "令其摸一张牌",
	["jl_dingzhen2"] = "此【杀】不计入次数限制",
	["jl_dingzhen3"] = "你失去1点体力",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["$bf_huangtian0"] = "%from 发动了 %arg 的“%arg2”",
	["jl_tianzi"] = "天子",
	["#jl_tianzi"] = "真命天子",
	["designer:jl_tianzi"] = "",
	["illustrator:jl_tianzi"] = "官方",
	["jl_weiye"] = "魏业",
	[":jl_weiye"] = "当你需要使用或打出【闪】时，你可以令其他「魏」势力角色打出（视为你使用或打出）；当其他「魏」势力角色的黑色判定牌生效后，其可以令你摸一张牌；当你陷入濒死状态时，其他「魏」势力角色可以令你回复1点体力，然后其受到1点伤害。",
	["jl_weiye:jl_weiye0"] = "魏业：你可以令 %src 回复1点体力，然后你受到1点伤害",
	["jl_weiye_card"] = "魏业：你可以打出一张【闪】视为 %src 使用或打出了【闪】",
	["jl_shuitu"] = "蜀图",
	[":jl_shuitu"] = "当你需要使用或打出【杀】时，你可以令其他「蜀」势力角色打出（视为你使用或打出）；准备阶段，若你的体力值为场上最少，你增加1点体力上限并回复1点体力，然后获得“激将”；你可以弃置一张牌发动“激将”，响应的角色摸一张牌。",
	["jl_shuitu_card"] = "蜀图：你可以打出一张【杀】视为 %src 使用或打出了【杀】",
	["jl_wuce"] = "吴策",
	[":jl_wuce"] = "其他「吴」势力角色对你使用【桃】的回复值+1；其他「吴」势力角色出牌阶段限一次，其可以与你拼点，若其没赢，你获得双方拼点牌；其他「吴」势力角色出牌阶段限一次，其使用【杀】结算后，其可以将之交给你，然后你可以令其摸一张牌。",
	["jl_wucevs"] = "吴策",
	[":jl_wucevs"] = "「吴」势力角色出牌阶段限一次，你可以与“吴策”角色拼点，若你没赢，其获得双方拼点牌；「吴」势力角色出牌阶段限一次，你使用【杀】结算后，你可以将之交给“吴策”角色，然后其可以令你摸一张牌。",
	["jl_qunli"] = "群力",
	[":jl_qunli"] = "其他「群」势力角色出牌阶段限一次，其可以将一张【闪】或【闪电】交给你；当其他「群」势力角色造成伤害后，其可以进行判定，若为♠，你回复1点体力；你的手牌上限+X（X为场上存活「群」势力角色数×2）。",
	["jl_qunlivs"] = "群力",
	[":jl_qunlivs"] = "「群」势力角色出牌阶段限一次，你可以将一张【闪】或【闪电】交给“群力”角色；你造成伤害后，你可以进行判定，若为♠，“群力”角色回复1点体力",
	["jl_made"] = "马德",
	["#jl_made"] = "一体马人",
	["designer:jl_made"] = "Lua学生",
	["illustrator:jl_made"] = "",
	["jl_mengma"] = "猛马",
	[":jl_mengma"] = "锁定技，你计算与其他角色的距离为1.",
	["jl_pangshu"] = "庞术",
	[":jl_pangshu"] = "当你使用的【杀】被抵消后，你可以弃置目标一张牌，然后若之不为装备牌，此【杀】依旧造成伤害。",
	["jl_ningma"] = "宁马",
	["#jl_ningma"] = "锦翻尤侠",
	["designer:jl_ningma"] = "Lua学生",
	["illustrator:jl_ningma"] = "",
	["jl_qixi"] = "骑袭",
	[":jl_qixi"] = "你可以将一张黑色牌当做【过河拆桥】使用，然后获得因此弃置的牌。",
	["jl_fenwei"] = "愤威",
	[":jl_fenwei"] = "限定技，当一张牌指定多名角色为目标是，你可以令此牌无效，然后获得之。",
	["jl_fenwei:jl_fenwei0"] = "愤威：你可以令此【%src】无效，然后获得之",
	["jl_caochong"] = "曹冲",
	["#jl_caochong"] = "仁爱神童",
	["designer:jl_caochong"] = "Notify",
	["illustrator:jl_caochong"] = "官方",
	["jl_chengxiang"] = "称象",
	[":jl_chengxiang"] = "准备阶段或当你受到伤害后，你可以选择以下一项（每轮每项限一次）：第1~13项：亮出牌堆顶四张牌，令一名角色获得其中点数之和不大于【1~13】的牌；第14~26项：依次弃置一名角色的牌，直到弃置的牌点数之和大于【1~13】。",
	["jl_renxin"] = "仁心",
	[":jl_renxin"] = "锁定技。当你陷入濒死状态时，若“称象”中可选选项大于1，则你回复体力值至1点，然后移除“称象”中的一个选项。",
	["jl_chengxiang0"] = "称象：请选择令一名角色获得这些牌",
	["jl_chengxiang1"] = "称象：请选择一名角色，然后依次弃置其的牌",
	["$jl_chengxiang2"] = "%from 选择了“%arg”中的第 %arg2 项",
	["jl_chengxiang:jlcx_"] = "第%src项",
	["jl_renxin:jlcx_"] = "第%src项",
	["$jl_renxin0"] = "%from 选择移除了“%arg”中的第 %arg2 项",
	["jl_guanyu"] = "关羽",
	["#jl_guanyu"] = "威震华夏",
	["designer:jl_guanyu"] = "lua学生",
	["illustrator:jl_guanyu"] = "官方",
	["jl_wusheng"] = "武圣",
	[":jl_wusheng"] = "你可以将一张红色牌当做【杀】使用或打出；然后若为使用，此【杀】无距离与次数限制，且不能被响应。",
	["$jl_wusheng_bf"] = "%to 不能响应 %from 使用的【%arg】",
	["jl_xingdaorong"] = "邢道荣",
	["#jl_xingdaorong"] = "三国之战神",
	["jl_wuyong"] = "无勇",
	[":jl_wuyong"] = "锁定技。你不能使用和打出基本牌。",
	["jl_wumou"] = "无谋",
	[":jl_wumou"] = "锁定技。你不能使用锦囊牌。",
	["jl_wudu"] = "无度",
	[":jl_wudu"] = "锁定技，你不能使用装备牌。",
	["jl_wuliang"] = "无量",
	[":jl_wuliang"] = "锁定技。当你死亡时，你令一名其他角色获得你所有的技能。",
	["jl_wuliang0"] = "无量；请选择一名其他角色获得你所有的技能。",
	["jl_handang"] = "韩当",
	["#jl_handang"] = "小作文の杀手",
	["jl_gongqi"] = "弓骑",
	[":jl_gongqi"] = "出牌阶段结束后，你可以弃置一张装备牌，然后执行一个额外的出牌阶段。",
	["jl_gongqi0"] = "弓骑：你可以弃置一张装备牌执行一个额外的出牌阶段",
	["jl_jiefan"] = "解烦",
	[":jl_jiefan"] = "出牌阶段限一次，你可以令一名角色选择：1、移除一个技能描述字数大于此技能的技能；2、变更武将牌。",
	["jl_jiefan1"] = "移除一个小作文技能",
	["jl_jiefan2"] = "变更武将牌",
	["jl_2_liubei"] = "刘备",
	["#jl_2_liubei"] = "汉中王",
	["designer:jl_2_liubei"] = "负俗之才",
	["illustrator:jl_2_liubei"] = "明暗交界",
	["jl_zebing"] = "择兵",
	[":jl_zebing"] = "主公技。你的第一个摸牌阶段结束时，你摸4张花色不同的牌，然后将一张♦牌当做“兵”置于武将牌上，将一张♣牌当做“粮”置于武将牌上，将一张♥牌当做“谋”置于武将牌上，将一张♠牌当做“器”置于武将牌上。出牌阶段开始时或结束阶段结束时，你可以将任意张牌分配至“兵”“粮”“谋”“器”中，或将“兵”“粮”“谋”“器”中任意张牌收回手牌；每个“兵”“粮”“谋”“器”中至多有4张牌。出牌阶段，你可以弃置一张“兵”“粮”“谋”"..
	"“器”牌并执行对应效果：若弃置了“兵”，则你令一名其他蜀势力角色交给你两张基本牌，然后其摸两张牌，否则你从场上或牌堆中随机获得两张基本牌；若弃置了“粮”，则你令一名其他角色交给你一张【桃】或【桃园结义】，否则你从场上或牌堆中随机获得一张【桃】；若弃置了“谋”，则你令一名其他蜀势力角色交给你两张锦囊牌，否则你从场上或牌堆中随机获得两张锦囊牌，且其中不为延时锦囊的牌你可以额外指定一名目标；若弃置了“器”，则你"..
	"令一名其他角色交给你一张武器牌，否则你从场上或牌堆中随机获得一张武器牌。当你发动此技能后，若你的体力值不为1，你因此获得的伤害牌造成的伤害+1，且此牌造成伤害后，你选择一项：⒈摸X张牌，⒉令目标弃置X张牌；⒊收回此牌并去除其附加效果。若你体力值为1，你可以将因此获得的牌当做【桃】使用，或交给一名蜀势力角色，然后你与其各摸一张牌。若你没有“兵”，你视为拥有“激将”；若你没有“粮”，普通【杀】对你无效；若"..
	"你没有“谋”，你不能成为普通锦囊牌的目标；若你没有“器”，所有不为蜀势力的角色视为在你的攻击范围内。当你陷入濒死状态时，你可以弃置一张“兵”并选择一名其他角色，若其不为蜀势力，则其可以将势力改为「蜀」，然后交给你一张牌；若其为蜀势力，则你将体力回复至1点；当你需要使用【桃】【酒】【闪】【无懈可击】时，你可以弃置一张“粮”，然后视为使用之。当你需要使用【五谷丰登】【万箭齐发】【南蛮入侵】【铁索连"..
	"环】【借刀杀人】时，你可以弃置一张“谋”，然后视为使用之；若你装备区有牌，则你使用【顺手牵羊】【过河拆桥】可以额外指定一个目标。当一名蜀势力角色打出【杀】/【南蛮入侵】造成伤害后，你可以弃置一张“兵”/“谋”，然后获得之；当一名角色使用【桃】或【酒】回复体力后，你可以弃置一张“粮”，然后获得之。当一张装备牌因其他角色弃置而进入弃牌堆时，你可以弃置一张“器”，然后获得之。",
	["jl_zebing0"] = "择兵：请选择将一张%src牌当做“%dest”置于武将牌上",
	["jl_zebing1"] = "选择目标交给你牌",
	["jl_zebing2"] = "视为使用牌",
	["jl_zebing3"] = "择兵：请执行--%src",
	["jl_zebing4"] = "择兵：请选择%dest张【%arg】交给 %src",
	["jl_zebing5"] = "择兵：请视为使用一张【%src】",
	["jl_bing"] = "兵",
	["jl_liang"] = "粮",
	["jl_mou"] = "谋",
	["jl_qi"] = "器",
	["jl_bing_effect"] = "选择令一名其他蜀势力角色交给你两张基本牌",
	["jl_liang_effect"] = "选择令一名其他角色交给你一张【桃】或【桃园结义】",
	["jl_mou_effect"] = "选择令一名其他蜀势力角色交给你两张锦囊牌",
	["jl_qi_effect"] = "选择令一名其他其他角色交给你一张武器牌",
	["jl_zebing20_effect"] = "选择令一名其他蜀势力角色获得此牌",
	["Peach,GodSalvation"] = "桃】或【桃园结义",
	["$jl_zebing0"] = "%card 来自“%arg”",
	["jl_zebing10"] = "将此牌当做【桃】使用",
	["jl_zebing20"] = "令一名其他蜀势力角色获得此牌",
	["jl_zebing_damage1"] = "摸等伤害值张牌",
	["jl_zebing_damage2"] = "伤害目标弃置等伤害值张牌",
	["jl_zebing_damage3"] = "收回此牌并去除附加效果",
	["jl_zebing:jl_zebing0"] = "择兵：你可以弃置“器”，然后选择获得弃置的装备牌",
	["jl_zebing01"] = "择兵：请选择将要获得的装备牌",
	["jl_zebing02"] = "择兵：请选择将要弃置的“器”牌",
	["jl_zebing21"] = "择兵：你可以弃置一张“%src”牌,然后获得此【%dest】",
	["jl_zebing11"] = "择兵：你可以弃置一张“兵”牌，然后选择一名其他角色",
	["jl_zebing12"] = "择兵：请选择一名其他角色",
	["jl_zebing11:jl_zebing13"] = "择兵：你可以将势力改为「蜀」，然后交给 %src 一张牌",
	["jl_jiuxuevs"] = "究学",
	[":jl_jiuxuevs"] = "平面直角坐标系内，存在y=-x/3+√3与Y轴相交于点A，与X轴相交于点B，点C处于Y轴上且直线CP垂直AB于点P，交Y轴于点C；点P的横坐标为3；在X轴上有一点E，使 S△ACE=1/2 S△ACP；出牌阶段开始时，你可以摸m张牌（m为点E的横坐标max，向上取整）。",
	["jl_jiuxuevs:jl_jiuxuevs0"] = "究学：平面直角坐标系内，存在y=-x/3+√3与Y轴相交于点A，与X轴相交于点B，点C处于Y轴上且直线CP垂直AB于点P，交Y轴于点C；点P的横坐标为3；在X轴上有一点E，使 S△ACE=1/2 S△ACP。你可以选择解出这道题，然后选择正确的答案；是否选择答案？",
	["#jl_jiuxuevs1"] = "%from 解出 %arg 的答案为 %arg2",
	["jl_jiuxuevs2"] = "正确",
	["jl_jiuxuevs3"] = "错误",
	["jl_chenshou"] = "陈寿",
	["#jl_chenshou"] = "浮笔显毫微",
	["designer:jl_chenshou"] = "紫髯的小乔",
	["illustrator:jl_chenshou"] = "三国志大战",
	["jl_zhendian"] = "正典",
	[":jl_zhendian"] = "使命技。出牌阶段开始时，你可以选择一项：1、搜寻或销毁一张智囊牌名的锦囊牌，摸两张牌；2、废除或恢复一个装备栏，将其中的牌置入“仁”区并回复1点体力。背水：先执行一次“整肃”。\n<font color=\"black\"><b>成功</b></font>：若游戏外的智囊牌名或装备牌副类别不少于三种，你获得游戏外的这些牌，将此技能改为转换技，选项1和2分别改为①和②效果。\n<font color=\"black\"><b>失败</b></font>：若你以此法“整肃”失败，则使命失败。",
	["jl_zhendian1"] = "搜寻或销毁一张智囊牌名的锦囊牌",
	["jl_zhendian2"] = "废除或恢复一个装备栏",
	["jl_zhendianvs"] = "正典",
	[":jl_zhendianvs"] = "转换技。出牌阶段开始时，你可以①搜寻或销毁一张智囊牌名的锦囊牌，摸两张牌②废除或恢复一个装备栏，将其中的牌置入“仁”区并回复1点体力。",
	[":jl_zhendianvs1"] = "转换技。出牌阶段开始时，你可以①搜寻或销毁一张智囊牌名的锦囊牌，摸两张牌<font color=\"#01A5AF\"><s>②废除或恢复一个装备栏，将其中的牌置入“仁”区并回复1点体力</s></font>。",
	[":jl_zhendianvs2"] = "转换技。出牌阶段开始时，你可以<font color=\"#01A5AF\"><s>①搜寻或销毁一张智囊牌名的锦囊牌，摸两张牌</s></font>②废除或恢复一个装备栏，将其中的牌置入“仁”区并回复1点体力。",
	["jl_zhendian3"] = "先执行一次“整肃”",
	["beishui_choice=jl_zhendian3"] = "背水 先执行一次“整肃”",
	["jl_zhendian4"] = "正典：你可以选择销毁一张智囊牌名的锦囊牌，否则将搜寻一张智囊牌名的锦囊牌",
	["jl_qianxue"] = "潜学",
	[":jl_qianxue"] = "蜀势力技。隐匿：你登场时弃置X张牌并施法：获得X点护甲。",
	["jl_qianxue0"] = "潜学：请弃置1~3张牌用以[施法]",
	["jl_chailu"] = "采录",
	[":jl_chailu"] = "晋势力技。强令：令一名其他角色交给你一张游戏外没有的非基本牌。\n<font color=\"black\"><b>成功</b></font>：其摸一张牌；\n<font color=\"black\"><b>失败</b></font>：此阶段结束时，你可以多发动一次“正典”。",
	["jl_chailu0"] = "采录-强令：请选择令一名其他角色交给你一张游戏外没有的非基本牌",
	["jl_chailu1"] = "采录-强令：请交给 %src 一张游戏外没有的非基本牌",
	["jl_siju"] = "排位四巨",
	["#jl_siju"] = "得心应手",
	["designer:jl_siju"] = "lua学生",
	["illustrator:jl_siju"] = "",
	["jl_shenchong"] = "神宠",
	["#jl_shenchong"] = "首刹的先知",
	["designer:jl_shenchong"] = "Lua学生",
	["illustrator:jl_shenchong"] = "",
	["jl_jiejun"] = "劫军",
	[":jl_jiejun"] = "当你使用【杀】指定目标时，你可以依次执行：1、摸一张牌（执行6次），2、将目标所有手牌扣置于其武将牌上（此回合结束时你获得这些牌），3、你交给目标一张牌，4、令此【杀】不计入次数，5、此【杀】结算后，你将之交给一名其他角色。",
	["jl_chousi"] = "筹思",
	[":jl_chousi"] = "出牌阶段限一次。你可以摸5张牌并受到1点伤害，然后进行一次判定，若为红色，你令一名其他角色摸两张牌，若为黑色，你弃置一名其他角色一张牌。",
	["jl_jiejun0"] = "劫军：请选择一名其他角色，将此【杀】交给其",
	["jl_chousi0"] = "筹思：请选择一名其他角色；红色，其摸两张牌；黑色，弃置其一张牌",
	["$jl_bingfen"] = "%from（玩家）启用了 %arg",
	["jl_bingfen"] = "缤芬模式",
	["jl_bingfen:jl_bingfen0"] = "你可以开启【缤芬模式】，是否开启【缤芬模式】？",
	["jl_shenci"] = "神赐",
	["#jl_shenci"] = "稀世大王霸",
	["designer:jl_shenci"] = "Lua学生",
	["illustrator:jl_shenci"] = "",
	["jl_jice"] = "激策",
	[":jl_jice"] = "每当你使用红色【杀】或【决斗】指定目标时，你可以依次执行：1、摸一张牌，2、对其造成1点伤害，3、进行判定，红色，你摸两张牌，黑色，弃置其区域内一张牌，4、观看其所有手牌并弃置其中每种花色各一张，5、若你的牌数大于其，此【杀】对其伤害+1。",
	["jl_xiongyi"] = "凶异",
	[":jl_xiongyi"] = "出牌阶段限一次。你可以令一名角色摸两张牌，然后对其造成2点伤害；若其因此阵亡，你选择获得一项技能：“当先”、“制蛮”。",
	["jl_kuangshe"] = "狂射",
	[":jl_kuangshe"] = "你可以将一张牌当做【杀】对所有其他角色使用，并摸等目标数张牌，然后依次获得这些角色区域内一张牌；结算后你将此【杀】置于牌堆顶。",
	["jl_xyy"] = "袭羊羊",
	["#jl_xyy"] = "懿谋羊勇",
	["designer:jl_xyy"] = "Lua学生",
	["illustrator:jl_xyy"] = "Lua学生",
	["jl_yangxi"] = "羊袭",
	[":jl_yangxi"] = "准备阶段，你可以对一名角色随机造成-2~2点伤害。",
	["jl_yangxi0"] = "羊袭：你可以选择一名角色造成伤害",
	["jl_yisuan"] = "懿算",
	[":jl_yisuan"] = "出牌阶段，你可以将武将牌替换为“吴懿”进行游戏；阶段结束后还原。",
	["jl_liuxu"] = "刘诩",
	["#jl_liuxu"] = "寰宇之极数",
	["designer:jl_liuxu"] = "",
	["illustrator:jl_liuxu"] = "",
	["jl_boji"] = "博极",
	[":jl_boji"] = "锁定技若厮刑主公于喋血汝受其倾朝权野之号予号者居咸位列是其牌漫五也汝崩之亦射毕若任伻他益命汝益其锦华佳人之号每其摸牌益之一二若者使锦囊之牌益三有四汝瓒其曰博极群书之号称卿挂相而不达于咸后二者终有此号且惟施于友",
	["jl_jiuxue"] = "究学",
	[":jl_jiuxue"] = "锁定技。设你此回合使用的牌数为X，你区域内的牌数为Y；若 (X,Y) 符合 Y=±(2X±X±1) ，则你将手牌摸至(±2X!±2,Y) 中Y的任意实数根张（Y≥0且向上取整）；若你以此法调整了3次手牌，你修改此技能。\n<font color=\"black\"><b>修改</b></font>：平面直角坐标系内，存在y=-x/3+√3与Y轴相交于点A，与X轴相交于点B，点C处于Y轴上且直线CP垂直AB于点P，交Y轴于点C；点P的横坐标为3；在X轴上有一点E，使 S△ACE=1/2 S△ACP；出牌阶段开始时，你可以摸m张牌（m为点E的横坐标max，向上取整）。",
	["jl_shiyi"] = "师夷",
	[":jl_shiyi"] = "While game start phase,you can target a character,skip the next turn of that character.When a character who is in your attack range uses a handcard,you can use a handcard with a same card-name. And if you uses at least 3 cards in this way,you can cause 1 damage to this character.",
	["jl_boji1"] = "倾朝权野",
	["jl_boji2"] = "锦华佳人",
	["jl_boji3"] = "博极群书",
	["jl_shiyi0"] = "Shiyi:You can choose a target",
	["jl_shiyi1"] = "Shiyi:You can use a 【%src】",
	["jl_sunce1"] = "孙策",
	["#jl_sunce1"] = "江东小王霸",
	["designer:jl_sunce1"] = "",
	["illustrator:jl_sunce1"] = "",
	[":jl_sunben"] = "觉醒技。当你体力上限为1时，你获得技能“魂姿”。",
	["jl_bashen"] = "八神",
	["#jl_bashen"] = "福禄永驻",
	["designer:jl_bashen"] = "",
	["illustrator:jl_bashen"] = "烧饼浪",
	["jl_wuxing"] = "五星上将",
	["#jl_wuxing"] = "热门首选",
	["designer:jl_wuxing"] = "",
	["illustrator:jl_wuxing"] = "",
	["$NotifySkillInvoked_1"] = "%from 发动了 “%arg” ，目标是 %to",
	["$NotifySkillInvoked_2"] = "%from 发动了 “%arg”",
	["up_hp"] = "回复体力",
	["jl_zhijun"] = "治军",
	[":jl_zhijun"] = "你可以将一张♣♠牌当【閷】使用\n<font color=\"black\"><b>閷 基本牌<br /><b>卡牌效果</b>：此牌可视为【杀】或【闪】使用。</b></font>",
	["__jl_sha"] = "閷",
	["jl_sha"] = "閷",
	[":__jl_sha"] = "基本牌<br /><b>卡牌效果</b>：此牌视为【杀】和【闪】的使用效果。",
	["jl_fushi"] = "赋诗",
	[":jl_fushi"] = "出牌阶段限一次，你可以弃置至少两张不同花色的手牌，然后选择摸等量的牌或回复1点体力",
	["jl_jianxiong"] = "奸雄",
	[":jl_jianxiong"] = "当你受到伤害后，你可以获得造成伤害的牌或对伤害来源使用一张【杀】",
	["jl_nengchen"] = "能臣",
	[":jl_nengchen"] = "锁定技，你的摸牌数等于体力上限",
	["jl_canzheng"] = "残政",
	[":jl_canzheng"] = "主公技，当你杀死一名角色后，你可以增加1点体力上限并回复1点体力",
	["jl_daishou"] = "代首",
	[":jl_daishou"] = "限定技，当你受到伤害时，你可以弃置任意张牌，然后令此伤害-X（X为你弃置的牌数）",
	["jl_bianjie"] = "变节",
	[":jl_bianjie"] = "觉醒技，准备阶段，若你造成或受到的伤害数累计大于你的体力上限，你扣减1点体力上限，然后你发动“奸雄”时可以摸一张牌",
	["jl_qiangzhen"] = "强阵",
	[":jl_qiangzhen"] = "转化技，若你的体力值大于4，你使用的杀数+X；若你的体力值不大于4，你的手牌上限+X（X为存活角色数）",
	["jl_yitian"] = "倚天",
	[":jl_yitian"] = "奋发技，当你造成伤害时，你可以回复1点体力 \n<font color=\"red\"><b>奋发技为体力值小于体力上限的一半时可发动（向下取整）</b></font>",
	["jl_shewei"] = "涉危",
	[":jl_shewei"] = "联动技，当一名角色发动“强袭”或“裸衣”时，你可以令你与其当中手牌数较小的一方摸一张牌",
	["jl_jixu"] = "击虚",
	[":jl_jixu"] = "转换技，当你使用[阳]基本牌/[阴]锦囊牌，指定目标后，若你的手牌数大于其，你可以令其无法响应",
	[":jl_jixu2"] = "转换技。当你使用<font color=\"#01A5AF\"><s>[阳]基本牌/</s></font>[阴]锦囊牌，指定目标后，若你的手牌数大于其，你可以令其无法响应",
	[":jl_jixu1"] = "转换技。当你使用[阳]基本牌<font color=\"#01A5AF\"><s>/[阴]锦囊牌</s></font>，指定目标后，若你的手牌数大于其，你可以令其无法响应",
	["jl_mengsha"] = "梦杀",
	[":jl_mengsha"] = "隐匿技，当你于其他角色回合登场后，你可以令当前回合角色扣减1点体力上限",
	["jl_jianshi"] = "剑誓",
	[":jl_jianshi"] = "使命技，当一名角色因你而进入濒死状态后<br />成功：若其死亡，你将“奸雄”中的“获得造成伤害的牌”改为“获得造成伤害的牌并摸一张牌”<br />失败：若其脱离濒死状态，你将“奸雄”中的“对伤害来源使用一张【杀】”改为“视为对伤害来源使用一张【杀】”",
	["jl_caocao"] = "曹操",
	["#jl_caocao"] = "魏武大帝",
	["designer:jl_caocao"] = "",
	["illustrator:jl_caocao"] = "官方",
	["jl_bianjie:jl_bianjie0"] = "你可以发动“变节”效果，摸一张牌",
	["jl_jianshi:jl_jianshi0"] = "你可以执行“剑誓”效果，视为对 %src 使用一张【杀】，否则你获得造成伤害的牌",
	["jl_jianxiong_slash"] = "奸雄：你可以对 %src 使用一张【杀】，否则你获得造成伤害的牌",
	["jl_daishou0"] = "代首：你可以弃置任意张牌，然后减少等量的伤害数",
	["jl_shewei0"] = "涉危：你可以令选择目标摸一张牌",
	["jl_lvxun"] = "吕逊",
	["#jl_lvxun"] = "强势酱油",
	["designer:jl_lvxun"] = "",
	["illustrator:jl_lvxun"] = "",
	["jl_yuji"] = "于吉",
	["designer:jl_yuji"] = "",
	["illustrator:jl_yuji"] = "官方",
	["#jl_yuji"] = "恶毒的道士",
	["jl_zhuzhou"] = "诅咒",
	[":jl_zhuzhou"] = "锁定技。杀死你的角色须执行三国杀最恶毒的诅咒--将武将牌替换为“孙策（山）”。",
	["jl_zhoutai"] = "周泰",
	["#jl_zhoutai"] = "肤如刻画",
	["designer:jl_zhoutai"] = "民间DIY",
	["illustrator:jl_zhoutai"] = "真三国无双",
	["jl_buhui"] = "不悔",
	[":jl_buhui"] = "锁定技。你不能成为【杀】和【桃】的目标。",
	["yao"] = "妖",
	["jl_wangtaoyue"] = "王桃悦",
	["#jl_wangtaoyue"] = "晔兮如莹",
	["designer:jl_wangtaoyue"] = "lua学生",
	["illustrator:jl_wangtaoyue"] = "",
	["jl_huguan"] = "护关",
	[":jl_huguan"] = "一名角色于其回合内使用第一张牌时，若为红色，你可以弃置一张牌，则其此回合内与你弃置牌花色相同的牌不计入手牌上限，然后若其弃牌阶段未弃牌，你摸一张牌。",
	["jl_luanpei"] = "鸾佩",
	[":jl_luanpei"] = "其他角色回合结束时，若此回合内有角色回复过体力，你可以弃置一张其未于弃牌阶段弃置过的花色的牌，则你令你们其中一名角色回复1点体力，然后手牌数较少的角色将手牌补至与另一名角色相同（至多补至5张）。",
	["jl_huguan0"] = "护关：你可以弃置一张牌，则 %src 此回合内与你弃置牌花色相同的牌不计入手牌上限",
	["jl_luanpei0"] = "鸾佩:你可以弃置一张 %src 未于弃牌阶段弃置过的花色的牌",
	["jl_luanpei1"] = "鸾佩：请选择你们其中一名角色回复1点体力",
	["jl_zhanshen"] = "三国战神",
	["designer:jl_zhanshen"] = "暴躁大宝",
	["illustrator:jl_zhanshen"] = "侠民",
	["#jl_zhanshen"] = "破军之矛",
	["jl_poying"] = "破营",
	[":jl_poying"] = "锁定技。当你使用【杀】指定目标时，你依次执行以下选项：⒈额外指定两名其他角色为目标；⒉目标所有技能失效，直至其回合结束；⒊将目标所有牌扣置于其武将牌上，回合结束时你获得之；⒋若你的手牌数大于目标，则此【杀】不能被其响应；⒌此【杀】伤害+X（X为你使用过的花色数和牌类型数）；⒍造成伤害时你摸5张牌；⒎本回合可以使用的【杀】数+1；⒏其他角色于你回合内陷入濒死状态时，你令其立即死亡。",
	["jl_shenji"] = "神骑",
	[":jl_shenji"] = "锁定技。你不能被翻面；其他角色回合开始前或结束后，你执行一个额外回合；摸牌阶段，你额外摸4张牌；出牌阶段，你使用的牌无距离限制且第一张牌不能被响应；弃牌阶段开始时，你选择：⒈将本回合手牌上限改为当前手牌数，⒉弃置任意张牌并弃置一名其他角色等量的牌，然后对其造成2点伤害。",
	["jl_longjiang"] = "龙将",
	[":jl_longjiang"] = "你的基本牌可以当任意基本牌使用或打出；准备阶段，你可以弃置任意张牌，然后弃置判定区内同颜色的牌。",
	["jl_shenji0"] = "神骑：你可以弃置任意张牌并弃置一名其他角色等量的牌，然后对其造成2点伤害，否则你将本回合手牌上限改为当前手牌数",
	["jl_longjiang0"] = "龙将：你可以弃置任意张牌，然后弃置判定区内同颜色的牌。",
	["jl_poying0"] = "破营：请额外指定两名其他角色为目标",
	["jl_huasuo"] = "华索",
	["designer:jl_huasuo"] = "lua学生",
	["illustrator:jl_huasuo"] = "",
	["#jl_huasuo"] = "冷血孑侠",
	["jl_jueqing"] = "绝情",
	[":jl_jueqing"] = "锁定技。你造成的伤害+1，且均视为体力流失。",
	["jl_xiefang"] = "撷芳",
	[":jl_xiefang"] = "锁定技。你计算与其他女性角色距离为1；女性角色不能响应你的牌。",
	["jl_heyan"] = "何晏",
	["designer:jl_heyan"] = "lua学生",
	["illustrator:jl_heyan"] = "",
	["#jl_heyan"] = "傅粉何娘",
	["jl_qingtan"] = "轻弹",
	[":jl_qingtan"] = "出牌阶段限一次。你可以令所有其他有手牌的角色各展示一张手牌，然后你获得这些展示的牌。",
	["jl_qingtan0"] = "轻弹：请选择一张手牌用于展示",
	["jl_yachai"] = "睚钗",
	[":jl_yachai"] = "当你受到其他角色的伤害后，你可以令其弃置一半的手牌（向上取整）并将剩余的手牌交给你。",
	["jl_erciyuan"] = "二次袁",
	["#jl_erciyuan"] = "兄弟患难",
	["designer:jl_erciyuan"] = "",
	["illustrator:jl_erciyuan"] = "官方",
	["jl_neifa"] = "内伐",
	[":jl_neifa"] = "出牌阶段限一次，你可以摸两张牌并将一张牌置于牌阶段顶或底部，然后将不同颜色的另一张牌置"..
	"于牌堆的另一端；若牌堆顶牌的颜色为：[阴]，红色，你从牌堆中摸三张不同类型的黑色牌并展示三张不同类型的黑色"..
	"牌；根据展示结果：y为偶数，你可以令至多x名角色各摸一张牌；y为奇数，你可以令至多x名角色各弃置一张牌；然后"..
	"若y可以被x整除（x为三张牌中最小的差且不为负数，y为点数之和），则你获得x枚“伐”标记（记为z）并可以于此阶段"..
	"内额外发动一次“内伐”且不能再选择[阴]。[阳]，黑色，你展示下家一张手牌，若为黑色，你获得之并令其摸或弃x张牌，"..
	"否则你展示其下家一张牌重复此流程，若无可展示的目标，你获得这些展示的红色牌并随机分配给对应的角色，此时若z等"..
	"于这些角色数，你可以弃置牌堆顶z张牌对这些角色各造成1点伤害，然后受到伤害的角色依次与你拼点，赢的角色可以终止"..
	"未开始的拼点并摸z张牌和弃置等量的牌，若弃置牌中有一张牌的颜色与其他牌颜色均不同，则其可以观看一名角色的手牌并"..
	"获得其中的一张异色牌，记录此牌为a，弃置的异色牌为b，若a点数>b点数，你令其将a置于牌堆顶并视为其发动“内伐”[阴]；"..
	"你可以令a点数+z后执行：计算a点数+b点数、a点数–b点数和a点数*b点数，记最大值为max，最小值为min，若 y=max*x^2+min*"..
	"x+a^2 有两个不相同的根，则你可以弃置一名角色至多（a点数–b点数）张牌并令b点数+等量的牌，若此时a点数等于b点数，你"..
	"下一次发动“内伐”可以额外将一张同色牌置于牌堆顶或底部且你可以令x、y、z、max、min、a点数、b点数随意+z或–z。此时若z"..
	"为3的倍数且大于8，你摸21张牌并将手牌数调整至21张并展示之，然后你可以将手牌按斗地主规则打出直到有人管得上你为止；"..
	"若以此法打出了所有手牌，你此阶段可以额外发动一次“内伐”且不能选择[阳]；若有人以此法管上了你且你要不起，你结束此阶"..
	"段，其获得一个额外回合且其出牌阶段开始时视为其发动一次“内伐”。",
	["jl_neifa0"] = "内伐：请选择一张牌",
	["jl_neifa01"] = "内伐：请选择另一张不同颜色的牌",
	["jl_neifa1"] = "内伐：请选择每种类型各一张的黑色牌",
	["jl_neifa02"] = "内伐：你可以额外选择一张牌按颜色置于牌堆顶或底部",
	["jl_neifa2"] = "内伐：你可以按点数之和 %dest 的奇偶令 %src 名角色摸牌或弃牌 ",
	["jl_neifa:jl_neifa4"] = "内伐：你可以弃置牌堆顶 %src 张牌，对这些角色各造成1点伤害",
	["jl_neifa:jl_neifa5"] = "内伐：你可以终止后面的拼点，然后摸 %src 张牌并弃置等量的牌",
	["jl_neifa6"] = "内伐：你可以观看一名角色的手牌并获得其中的一张异色牌",
	["$jl_neifa7"] = "函数：%arg 在实数域 %arg1 两个不相同的根",
	["no_jl_neifa7"] = "没有",
	["yes_jl_neifa7"] = "有",
	["jl_neifa8"] = "内伐：你可以选择弃置一名角色至多 %src 张牌",
	["jl_DouDiZhu"] = "斗地主",
	["jl_DouDiZhu0"] = "斗地主：请选择牌打出",
	["jl_DouDiZhu1"] = "斗地主：你可以响应 %src ，打出大于其的牌",
	["a_to_z"] = "令a点数+z（z为“伐”数）",
	["jl_fa"] = "伐",
	["  "] = "  ",
	["jl_zhouyu"] = "周瑜",
	["#jl_zhouyu"] = "大嘟嘟",
	["designer:jl_zhouyu"] = "lua学生",
	["illustrator:jl_zhouyu"] = "",
	["jl_xiongzi"] = "雄姿",
	[":jl_xiongzi"] = "摸牌阶段，你可以额外摸X张牌。（X为场上女性角色数）",
	["jl_xixiong"] = "袭凶",
	[":jl_xixiong"] = "出牌阶段每名女性角色限一次。你可以观看一名女性角色的所有手牌，选择获得其中一种花色的所有牌，然后其摸等量的牌。",
	["jl_shenma"] = "神马",
	["designer:jl_shenma"] = "lua学生",
	["illustrator:jl_shenma"] = "lua学生",
	["#jl_shenma"] = "都是浮云",
	["jl_shenzhu"] = "神助",
	[":jl_shenzhu"] = "锁定技。你触发以下技能：<br />“铁骑”、“散谣”、“制蛮”、“抚蛮”、“自书”、“应援”、“潜袭”；<br />你计算与其他角色距离-2。",
	["fuman_to"] = "抚蛮-目标",
	["sanyao_hand"] = "散谣-最大手牌",
	["sanyao_hp"] = "散谣-最大体力",
	["jl_zhaoyun"] = "赵云完全体",
	["&jl_zhaoyun"] = "赵云",
	["#jl_zhaoyun"] = "游刃有余",
	["jl_wuyi"] = "吴懿",
	["designer:jl_wuyi"] = "lua学生",
	["illustrator:jl_wuyi"] = "lua学生",
	["#jl_wuyi"] = "乱世名将",
	["jl_mingqi"] = "名气",
	[":jl_mingqi"] = "当你于回合内使用非装备牌指定目标后，你可以弃置不为此牌目标的一名角色一张牌，然后其摸一张牌。出牌阶段限一次，当你使用的锦囊牌进入弃牌堆后，你可以减1点体力上限收回之。你于出牌阶段内对一名其他角色造成伤害后，你可以废除一个装备栏并选择其一个技能（限定技、觉醒技、主公技除外），则其下回合结束前此技能无效，然后你于其下回合结束或其死亡前拥有此技能且此期间内不能再发动此效果。当你受到1点伤害后，你可以将一张牌当做“锋”置于武将牌上；准备阶段开始时你移去所有“锋”，摸2X张牌，然后本回合你可以使用【杀】数+X（X为本回合移去“锋”的数量）。结束阶段开始时，你随机观看一名其他角色的X张随机手牌（X为全场手牌数最少的角色手牌数）；然后你可以令一名其他角色从牌堆中获得一张♥基本牌，若其于上回合成为过此效果的目标，其失去1点体力。一名其他角色的出牌阶段开始时，你可以摸两张牌，然后交给其两张牌，则本阶段结束后，若其未于本阶段杀死过一名角色，你失去1点体力。",
	["jl_mingqi:jl_mingqi1"] = "名气：你可以失去1点体力上限，收回【%src】",
	["jl_mingqi:jl_mingqi2"] = "名气：你可以将一张牌当做“锋”置于武将牌上",
	["jl_mingqi3"] = "名气：请选择一张牌当做“锋”置于武将牌上",
	["jl_mingqi4"] = "名气：你可以令一名其他角色从牌堆中获得一张♥基本牌",
	["jl_mingqi:jl_mingqi5"] = "名气：你可以摸两张牌，然后交给 %src 两张牌",
	["jl_mingqi0"] = "名气：你可以弃置不为此【%src】目标的一名角色的一张牌，然后其摸一张牌",
	["jl_mingqi_feng"] = "锋",
	["jl_mingqi6"] = "名气：请选择交给 %src 两张牌",
	["jl_mingqi7"] = "名气：你可以令一名其他角色选择是否交给你一张牌",
	["jl_mingqi8"] = "名气：你可以交给 %src 一张牌，然后其视为使用一张【%dest】",
	["jl_mingqi9"] = "名气：请视为使用一张【%src】",
	["jl_ceyu"] = "策瑜",
	["designer:jl_ceyu"] = "lua学生",
	["illustrator:jl_ceyu"] = "",
	["#jl_ceyu"] = "江东英秀",
	["jl_jiaoxin"] = "交心",
	[":jl_jiaoxin"] = "出牌阶段，若你已受伤且体力值为1，你可以摸一张牌并回复1点体力。",
	["jl_xusheng"] = "徐盛",
	["designer:jl_xusheng"] = "lua学生",
	["illustrator:jl_xusheng"] = "",
	["#jl_xusheng"] = "无常索命",
	["jl_judao"] = "菊刀",
	[":jl_judao"] = "锁定技。若你未装备武器，你视为装备着【古锭刀】。",
	["jl_zhuanhuaqi"] = "转化器",
	["#jl_zhuanhuaqi"] = "戏法大师",
	["designer:jl_zhuanhuaqi"] = "lua学生",
	["illustrator:jl_zhuanhuaqi"] = "lua学生",
	["jl_xishua"] = "戏耍",
	[":jl_xishua"] = "你可以发动以下技能：<br />“蛊惑”、“奇策”、“龙魂”、“奇袭”、“断粮”、“国色”、“武圣”、“龙胆”、“急救”、“火计”、“看破”、“连环”、“急袭”、“乱击”、“酒池”、“双雄”、“倾国”；然后将以此法造成伤害的牌当做“田”置于武将牌上。",
	["jl_xishua0"] = "戏耍：发动“%src” ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["#NOGuhuoQuery"] = "%from 体力值不大于0，不能 %arg",
	["jl_wudaoshi"] = "五道士",
	["#jl_wudaoshi"] = "通天化地",
	["designer:jl_wudaoshi"] = "lua学生",
	["illustrator:jl_wudaoshi"] = "lua学生",
	["jl_daoshu"] = "道术",
	[":jl_daoshu"] = "你可以于相应时机发动以下技能：<br />“雷击”、“鬼道”、“化身”、“新生”、“蛊惑”、“咒缚”、“影兵”、“义舍”、“布施”、“米道”",
	["@jl_daoshu"] = "道术：请选择一张手牌蛊惑【%src】",
	["guhuo_question:question0"] = "%src 选择了蛊惑【%dest】,是否质疑？",
	["jl_yingziy"] = "英姿",
	[":jl_yingziy"] = "摸牌阶段，你可以额外摸一张牌。",
	["jl_jiangy"] = "激昂",
	[":jl_jiangy"] = "每当你指定或成为【决斗】或红色【杀】的目标后，你可以摸一张牌。",
	["jl_miansha"] = "面杀之主",
	["#jl_miansha"] = "神之右手",
	["designer:jl_miansha"] = "lua学生",
	["illustrator:jl_miansha"] = "官方",
	["jl_yegui"] = "越规",
	[":jl_yegui"] = "你可以跳过判定阶段,并将判定区的牌弃置；摸牌阶段，你可以额外摸一张牌；出牌阶段，你可以观看相邻角色的手牌；弃牌阶段，若你的手牌数不为场上最多，你可以跳过弃牌；你使用牌无距离限制；每当【顺手牵羊】或【过河拆桥】对你生效时，你可以将任意张手牌置于武将牌上，此牌结算后你收回之；多目标锦囊生效时，你可以使用【无懈可击】抵消所有效果；【决斗】过程中，你可以使用【无懈可击】抵消效果；其他角色出牌阶段开始时，若你已受伤，你可以使用【桃】；回合结束后，你可以回复1点体力；你的使用属性【杀】伤害+1。",
	["jl_yegui0"] = "越规：你成为了【%src】的目标，可以选择将任意张手牌置于武将牌上",
	["jl_yegui1"] = "越规：你已受伤，可以使用一张【%src】",
	["jl_yegui:jl_yegui2"] = "越规：你可以额外摸一张牌",
	["jl_yegui:jl_yegui3"] = "越规：你已受伤，可以回复1点体力",
	["jl_yegui:jl_yegui4"] = "越规：你可以跳过判定阶段,然后将判定区的牌弃置",
	["jl_yegui:jl_yegui5"] = "越规：你的手牌数不为场上最多，你可以跳过弃牌",
	["  "] = "  ",
	["jl_liuyan"] = "刘焉",
	["#jl_liuyan"] = "立墓为志",
	["designer:jl_liuyan"] = "lua学生",
	["illustrator:jl_liuyan"] = "",
	["jl_tuse"] = "图涩",
	[":jl_tuse"] = "你使用牌指定目标后，你可以摸X张牌。（X为目标中包含的其他角色数）",
	["jl_limu"] = "立墓",
	[":jl_limu"] = "出牌阶段，若你的判定区没有“墓”，你可以将一张牌当作“墓”置于判定区，判定阶段时进行判定，若颜色相同，你失去所有体力，判定结束后弃置“墓”；若你拥有“墓”，你使用牌无距离与次数限制。",
	["__jl_mu"] = "墓",
	["jl_tuse:jl_tuse0"] = "你可以发动“图涩”摸 %src 张牌",
	["jl_womensa"] = "我们仨",
--	["&jl_womensa"] = "嘉才叡",
	["#jl_womensa"] = "太强了",
	["designer:jl_womensa"] = "lua学生",
	["illustrator:jl_womensa"] = "lua学生",
	["jl_xingtuo"] = "兴拓",
	[":jl_xingtuo"] = "当你陷入濒死状态后，你可以令所有其他同势力的角色选择是否受到1点伤害令你回复1点体力。当你受到伤害后，你可以令一名角色进行一次判定，若结果为：红色，其回复1点体力；黑色，其摸X张牌（X为此次伤害数）。",
	["jl_xianchou"] = "先筹",
	[":jl_xianchou"] = "锁定技。当你不因此技能而受到伤害后，你受到等量伤害；当你不因此技能而回复体力后，你回复等量体力；当你受到伤害后，你进行一次判定，若结果为：黑色，弃置一名角色区域内一张牌；红色，令一名角色摸一张牌（若为你则摸两张）。",
	["jl_xingtuo0"] = "兴拓：你可以令一名角色进行判定----若结果为：红色，其回复1点体力；黑色，其摸X张牌（X为此次伤害数）",
	["jl_xianchou0"] = "先筹：请选择一名角色执行效果----黑色，弃置一名角色区域内一张牌；红色，令一名角色摸一张牌（若为你则摸两张）",
	["jl_yuerqiao"] = "瑜二乔",
	["#jl_yuerqiao"] = "赤壁的火欲",
	["designer:jl_yuerqiao"] = "lua学生",
	["illustrator:jl_yuerqiao"] = "",
	["jl_sexiang"] = "色香",
	[":jl_sexiang"] = "出牌阶段，你可以一张♦牌当【乐不思蜀】对自己使用，然后你获得“激昂”。其他角色受到伤害时，你可以弃置一张♥手牌将此伤害转移给你，然后你获得“英姿”。（若已拥有对应技能，则该技能摸牌数值+1）",
	["jl_yanyin"] = "炎音",
	[":jl_yanyin"] = "每轮限一次。你可以弃置至少两张手牌令场上所有角色回复1点体力或受到1点火焰伤害。",
	["jl_yanyin1"] = "全场伤害",
	["jl_yanyin2"] = "全场回复",
	["jl_sexiang0"] = "色香：你可以弃置一张 %src 手牌将 %dest 受到的伤害转移给你",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["$jl_lianhuansr"] = "%from 为 %to 选择使用【%arg2】的目标为 %arg",
	["$tianzhai"] = "%from 的延时锦囊【%arg】开始判定",
	["jl_wuxiesy-use"] = "你可以使用【无懈生有】抵消 %src 对 %dest 效果，然后摸两张牌。",
	["jl_wuxiesyuse"] = "你可以使用【%dest】抵消 %src 效果，然后摸两张牌。",
	["#YinshiProtect"] = "%from 的“<font color=\"yellow\"><b>隐士</b></font>”效果被触发，防止了 %arg 点伤害[%arg2]",
	["jl_sandazhugong"] = "三大主公",
--	["&jl_sandazhugong"] = "曹刘孙",
	["#jl_sandazhugong"] = "三分天下",
	["designer:jl_sandazhugong"] = "BOBO",
	["illustrator:jl_sandazhugong"] = "BOBO",
	["jl_youka"] = "游卡",
	["#jl_youka"] = "罄竹难书",
	["designer:jl_youka"] = "lua学生",
	["jl_wuma"] = "无马",
	[":jl_wuma"] = "锁定技。你始终废除坐骑栏；你的坐骑牌视为【无中生有】；你受到【杀】的伤害时，若来源装备【麒麟弓】，此伤害+1。",
	["jl_pianke"] = "骗氪",
	[":jl_pianke"] = "出牌阶段，若你没有“盒子”，你可以将至少一张手牌当作“盒子”置于武将牌上，然后摸等量的牌；一名其他角色出牌阶段开始时，若你有“盒子”且其有手牌，你可以令其交给你一张手牌，则其随机获得你一张“盒子”，然后若这两张牌点数不同，其受到1点伤害，否则你失去1点体力。",
	["pianke"] = "盒子",
	["jl_yinbing"] = "阴兵",
	[":jl_yinbing"] = "每名角色回合限一次。你可以视为使用或打出一张基本牌或非延时锦囊牌，然后对一名其他角色造成1点伤害。",
	["jl_zhugong"] = "主公",
	[":jl_zhugong"] = "主公技。当你需要使用或打出一张【杀】或【闪】时，你可以令其他魏蜀吴势力角色打出一张【杀】或【闪】（视为由你使用或打出）；其他魏蜀吴势力角色对你使用的【桃】回复值+1。",
	["#jl_zhugonguse"] = "%from %arg 选择使用【%arg1】的目标为 %to",
	["@jl_zhugong-card"] = "你可以替 %src 出 %dest",
	["#jl_yeduj"] = "延时锦囊",
	["jl_sizhugong"] = "四群主公",
--	["&jl_sizhugong"] = "张董袁",
	["#jl_sizhugong"] = "群之霸者",
	["designer:jl_sizhugong"] = "BOBO",
	["illustrator:jl_sizhugong"] = "BOBO",
	["  "] = "  ",
	["jl_sanyuanse"] = "三原色",
--	["&jl_sanyuanse"] = "周魏曹",
	["#jl_sanyuanse"] = "人肉沙包",
	["designer:jl_sanyuanse"] = "BOBO",
	["illustrator:jl_sanyuanse"] = "BOBO",
	["  "] = "  ",
	["jl_wuhujiang"] = "五虎上将",
--	["&jl_wuhujiang"] = "关张赵马黄",
	["#jl_wuhujiang"] = "蜀之脊梁",
	["designer:jl_wuhujiang"] = "BOBO",
	["illustrator:jl_wuhujiang"] = "BOBO",
	["  "] = "  ",
	["jl_wuguogai"] = "吴国盖",
--	["&jl_wuguogai"] = "吴国盖",
	["#jl_wuguogai"] = "郎情妾意",
	["designer:jl_wuguogai"] = "BOBO",
	["illustrator:jl_wuguogai"] = "BOBO",
	["  "] = "  ",
	["jl_yuxun"] = "于逊",
--	["&jl_yuxun"] = "于逊",
	["#jl_yuxun"] = "不败的存在",
	["designer:jl_yuxun"] = "BOBO",
	["illustrator:jl_yuxun"] = "BOBO",
	["  "] = "  ",
	["jl_zhenjiao"] = "甄角",
--	["&jl_zhenjiao"] = "甄角",
	["#jl_zhenjiao"] = "天公美人",
	["designer:jl_zhenjiao"] = "qazxcvbnm11100",
	["illustrator:jl_zhenjiao"] = "qazxcvbnm11100",
	["  "] = "  ",
	["jl_zgyy"] = "诸葛月英",
--	["&jl_zgyy"] = "诸葛月英",
	["#jl_zgyy"] = "奇才卧龙",
	["designer:jl_zgyy"] = "BOBO",
	["illustrator:jl_zgyy"] = "BOBO",
	["jl_wumeinv"] = "五美女",
--	["&jl_wumeinv"] = "甄貂乔乔孙",
	["#jl_wumeinv"] = "当世绝色",
	["designer:jl_wumeinv"] = "BOBO",
	["illustrator:jl_wumeinv"] = "BOBO",
	["jl_qingshen"] = "倾神",
	[":jl_qingshen"] = "你可以将一张黑色手牌当【闪】使用或打出。准备阶段开始时，你可以进行一次判定，若判定结果为黑色，你获得生效后的判定牌且你可以重复此流程。",
	["jl_liyue"] = "离月",
	[":jl_liyue"] = "出牌阶段限一次，你可以弃置一张牌并选择两名男性角色：若如此做，视为其中一名角色对另一名角色使用一张【决斗】。结束阶段开始时，你可以摸一张牌。",
	["jl_liuse"] = "流色",
	[":jl_liuse"] = "你可以将一张♦牌当【乐不思蜀】使用。当你成为【杀】的目标时，你可以弃置一张牌，将此【杀】转移给你攻击范围内的一名其他角色（此【杀】的使用者除外）。",
	["@jl_liuse"] = "你可以弃置一张手牌将 %src 的【杀】的目标转移给你攻击范围内的一名其他角色",
	["jl_tianyan"] = "天颜",
	["jl_tianyanbf"] = "天颜",
	["@jl_tianyan-card"] = "你可以弃置一张♥手牌将此伤害转移给一名其他角色",
	[":jl_tianyan"] = "当你受到伤害时，你可以弃置一张♥手牌，将此伤害转移给一名其他角色，然后该角色摸X张牌（X为该角色已损失的体力值）。你的♠牌均视为♥牌。",
	["jl_xiaoyin"] = "枭姻",
	[":jl_xiaoyin"] = "出牌阶段限一次，你可以弃置两张手牌并选择一名已受伤的男性角色，你和该角色各回复1点体力。每当你失去一张装备区的装备牌后，你可以摸两张牌",
	["jl_wuzhinang"] = "五智囊",
--	["&jl_wuzhinang"] = "懿嘉彧植华",
	["#jl_wuzhinang"] = "魏之奇才",
	["designer:jl_wuzhinang"] = "BOBO",
	["illustrator:jl_wuzhinang"] = "BOBO",
	["jl_guikui"] = "鬼馈",
	[":jl_guikui"] = "每当一名角色的判定牌生效前，你可以打出一张手牌代替之。每当你受到伤害后，你可以获得伤害来源的一张牌。",
	["jl_tianji"] = "天计",
	[":jl_tianji"] = "你的判定牌生效后，你可以获得此牌。每当你受到1点伤害后，你可以观看牌堆顶的两张牌，然后将这两张牌任意分配。",
	["jl_quming"] = "驱命",
	[":jl_quming"] = "出牌阶段限一次，你可以与一名体力值大于你的角色拼点：若你赢，其对其攻击范围内你选择的另一名角色造成1点伤害。若你没赢，其对你造成1点伤害。每当你受到1点伤害后，你可以令一名角色将手牌补至X张（X为该角色的体力上限且至多为5）。",
	["jl_luoshi"] = "落诗",
	[":jl_luoshi"] = "若你武将牌正面朝上，你可以翻面视为使用一张【酒】；当你受到伤害后，若你的武将牌背面朝上，你可以将你的武将牌翻至正面朝上。其他角色的牌因判定或弃置而置入弃牌堆时，你可以获得其中至少一张♣牌。",
	["jl_shangqing"] = "伤情",
	[":jl_shangqing"] = "当你的手牌数小于X时，你可以将手牌补至X张（X为你已损失的体力值）。锁你造成的伤害均视为失去体力。",
	["  "] = "  ",
	["jl_lvbu"] = "完全体吕布",
	["&jl_lvbu"] = "吕布",
	["#jl_lvbu"] = "暴怒修罗战神",
	["designer:jl_lvbu"] = "BOBO",
	["illustrator:jl_lvbu"] = "BOBO",
	["jl_simaji"] = "司马姬",
--	["&jl_simaji"] = "司马姬",
	["#jl_simaji"] = "绝幸的天命",
	["designer:jl_simaji"] = "lua学生",
	["illustrator:jl_simaji"] = "lua学生",
	["jl_dengren"] = "邓仁",
--	["&jl_dengren"] = "邓仁",
	["#jl_dengren"] = "无尽的回合",
	["designer:jl_dengren"] = "BOBO",
	["illustrator:jl_dengren"] = "BOBO",
	["jl_zhugeliang"] = "诸葛亮完全体",
	["&jl_zhugeliang"] = "诸葛亮",
	["#jl_zhugeliang"] = "忠智冠三国",
	["designer:jl_zhugeliang"] = "BOBO",
	["illustrator:jl_zhugeliang"] = "BOBO",
	["jl_qizhang"] = "七张",
--	["&jl_qizhang"] = "七张",
	["#jl_qizhang"] = "智勇兼备",
	["designer:jl_qizhang"] = "BOBO",
	["illustrator:jl_qizhang"] = "BOBO",
	["jl_leidao"] = "雷道",
	[":jl_leidao"] = "每当一名角色的判定牌生效前，你可以打出一张黑色牌替换之。当你使用或打出一张【闪】后，你可以令一名角色进行一次判定，若判定结果为♠，你对其造成2点雷电伤害。",
	["jl_zhizheng"] = "直政",
	[":jl_zhizheng"] = "出牌阶段，你可以将手牌中的一张装备牌置于一名其他角色装备区内：若如此做，你摸一张牌。其他角色的弃牌阶段结束时，你可以将该角色于此阶段内弃置的一张牌从弃牌堆返回其手牌，若如此做，你可以获得弃牌堆里其余于此阶段内弃置的牌。",
	["jl_sijin"] = "四禁",
--	["&jl_sijin"] = "孙华吕曹",
	["#jl_sijin"] = "官方承认",
	["designer:jl_sijin"] = "BOBO",
	["illustrator:jl_sijin"] = "BOBO",
	["jl_lubei"] = "陆备",
--	["&jl_lubei"] = "陆备",
	["#jl_lubei"] = "牌堆全给你",
	["designer:jl_lubei"] = "BOBO",
	["illustrator:jl_lubei"] = "BOBO",
	["jl_sanjunshi"] = "三军师",
--	["&jl_sanjunshi"] = "司马郭荀",
	["#jl_sanjunshi"] = "大魏良材",
	["designer:jl_sanjunshi"] = "BOBO",
	["illustrator:jl_sanjunshi"] = "BOBO",
	["jl_weimou"] = "魏谋",
	[":jl_weimou"] = "每当你受到1点伤害后，你可以令一名角色将手牌补至X张（X为该角色的体力上限且至多为5），然后你可以观看牌堆顶的两张牌，然后分配这些牌。当你受到伤害后，你可以获得伤害来源的一张牌。",
	["jl_sidudu"] = "四都督",
--	["&jl_sidudu"] = "瑜肃蒙逊",
	["#jl_sidudu"] = "吴之屏障",
	["designer:jl_sidudu"] = "BOBO",
	["illustrator:jl_sidudu"] = "BOBO",
	["jl_yingjian"] = "英间",
	[":jl_yingjian"] = "摸牌阶段，你可以额外摸一张牌。出牌阶段限一次，若你有手牌，你可以令一名其他角色选择一种花色，然后其获得你一张手牌，若此牌花色与其选择的花色不同，则其受到1点伤害。",
	["jl_haomeng"] = "好盟",
	[":jl_haomeng"] = "摸牌阶段，你可以额外摸两张牌，然后若你的手牌多于五张，则将一半（向下取整）的手牌交给全场手牌数最少的一名其他角色。出牌阶段限一次，你可以弃置任意数量的牌并选择两名手牌数差等于该数量的其他角色：若如此做，这两名角色交换他们的手牌。",
	["jl_qianying"] = "谦营",
	[":jl_qianying"] = "每当你失去最后的手牌后，你可以摸一张牌。你不能被选择为【顺手牵羊】和【乐不思蜀】的目标。",
	["jl_jiangjiao"] = "姜角",
--	["&jl_jiangjiao"] = "姜角",
	["#jl_jiangjiao"] = "自欠收拾",
	["jl_sihai"] = "宇宙四害",
	["&jl_sihai"] = "四害",
	["#jl_sihai"] = "打我呀",
	["designer:jl_sihai"] = "吃蛋挞的折棒",
	["illustrator:jl_sihai"] = "吃蛋挞的折棒",
	["jl_liuxz"] = "刘玄奘",
--	["&jl_liuxz"] = "刘玄奘",
	["#jl_liuxz"] = "聪明绝顶",
	["designer:jl_liuxz"] = "阎魔老非酋",
	["illustrator:jl_liuxz"] = "阎魔老非酋",
	["jl_hongfa"] = "弘法",
	[":jl_hongfa"] = "限定技。出牌阶段，你可以将所有牌交给一名其他角色，视为使用一张基本牌，然后失去“仁望”获得“仁德”，若以此法交出的牌数大于2，你扣减1点体力上限回复1点体力。",
	["jl_shensunben"] = "神孙笨",
	["#jl_shensunben"] = "究极激昂",
	["jl_kuangang"] = "狂昂",
	[":jl_kuangang"] = "当你对距离为1的角色造成伤害后，你可以发动一次“激昂”。",
	["jl_yingang"] = "英昂",
	[":jl_yingang"] = "摸牌阶段，你可以发动一次“激昂”。",
	["jl_wangang"] = "忘昂",
	[":jl_wangang"] = "当你对其他角色造成1点伤害或受到其他的1点伤害后，你可以与该角色各发动一次“激昂”。",
	["jl_kuang"] = "苦昂",
	[":jl_kuang"] = "出牌阶段，你可以失去1点体力然后发动一次“激昂”。",
	["jl_fanang"] = "反昂",
	[":jl_fanang"] = "当你受到1点伤害后，你可以对来源发动一次“激昂”。",
	["jl_keang"] = "克昂",
	[":jl_keang"] = "若你未于出牌阶段内使用过【杀】，你可以发动一次“激昂”。",
	["jl_guiang"] = "归昂",
	[":jl_guiang"] = "当你受到1点伤害后,你可以对每名有牌的其他角色发动一次“激昂”。",
	["jl_guang"] = "蛊昂",
	[":jl_guang"] = "你可以扣置一张手牌当做任意一张基本牌或普通锦囊牌使用或打出；其他角色可以质疑并翻开此牌；若为真则你发动一次“激昂”，若为假则质疑的角色各发动一次“激昂”。",
	["jl_qiangang"] = "强昂",
	[":jl_qiangang"] = "出牌阶段限一次。你可以弃置一张武器牌或失去1点体力，然后发动一次“激昂”。",
	["jl_zhiang"] = "制昂",
	[":jl_zhiang"] = "主公技。其他吴势力角色出牌阶段限一次。该角色可以使你发动一次“激昂”。",
	["jl_zhiangPindian"] = "制昂",
	[":jl_zhiangPindian"] = "出牌阶段限一次。你可以令一名“制昂”角色发动一次“激昂”。",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["jl_hunzi"] = "魂姿",
	[":jl_hunzi"] = "  ",
	["jl_shawo"] = "杀我啊",
	["&jl_shawo"] = "杀我",
	["#jl_shawo"] = "杀我教教主",
	["jl_huanggaigai"] = "黄盖盖",
	["$jl_huanggaigai"] = "黄盖盖",
	["#jl_huanggaigai"] = "贯通古今",
	["designer:jl_huanggaigai"] = "lua学生",
	["illustrator:jl_huanggaigai"] = "lua学生",
	["jl_sancao"] = "三曹",
--	["&jl_sancao"] = "三曹",
	["#jl_sancao"] = "建安风骨",
	["designer:jl_sancao"] = "lua学生",
	["illustrator:jl_sancao"] = "lua学生",
	["jl_qizi"] = "七子",
	["&jl_qizi"] = "七子",
	["#jl_qizi"] = "  ",
	["jl_caoshi1"] = "曹",
	["jl_caoyi"] = "曹裔",
	["&jl_caoyi"] = "曹裔",
	["#jl_caoyi"] = "大魏帝裔",
	["jl_caoshi"] = "曹式",
	[":jl_caoshi"] = "  ",
	["jl_liubei"] = "刘备",
--	["&jl_liubei"] = "刘备",
	["#jl_liubei"] = "乱世的强盗",
	["designer:jl_liubei"] = "lua学生",
	["illustrator:jl_liubei"] = "",
	["jl_deren"] = "得仁",
	[":jl_deren"] = "出牌阶段，你可以令一名其他角色将任意张手牌交给你，若其于本阶段内以此法首次给出的手牌数少于两张，其失去1点体力。",
	["@jl_deren"] = "你可以交给 %src 任意张手牌",
	["jl_qiangji"] = "枪激",
	[":jl_qiangji"] = "当其他角色需要使用或打出【杀】时，你可以替其使用或打出【杀】。",
	["@jl_qiangji"] = "你可以替 %src 使用或打出【杀】",
	["jl_qiangjiVS"] = "枪激",
	[":jl_qiangjiVS"] = "当你需要使用或打出【杀】时，“枪激”角色可以替你使用或打出【杀】。",
	["  "] = "  ",
	["jl_wangba"] = "王八狮子甲",
	[":jl_wangba"] = "装备牌·防具<br /><b>装备效果</b>：锁定技。【南蛮入侵】、【万箭齐发】和普通【杀】对你无效；每当你受到火焰伤害时，此伤害+1；黑色【杀】对你无效；每当你受到伤害时，若此伤害大于1点，防止多余的伤害，每当你失去装备区里的【王八狮子甲】后，你回复1点体力。<br />每当你需要使用或打出一张【闪】时，你可以进行一次判定：若结果为红色，视为你使用或打出了一张【闪】。",
	["jl_guanbingcj"] = "贯冰插菊剑",
	[":jl_guanbingcj"] = "装备牌·武器<br /><b>装备效果</b>：你的【杀】无视目标的防具，且造成伤害时，若目标没有手牌，此伤害+1。你使用【杀】为最后的手牌时，可以额外选择至多两名目标；每当你使用的【杀】被【闪】抵消后，你可以弃置两张牌令此【杀】继续造成伤害；每当你使用【杀】对目标角色造成伤害时，若该角色有牌，你可以防止此伤害，然后依次弃置其两张牌。",
	["jl_guanbingcj:choice4"] = "你可以发动“贯冰插菊剑”防止此伤害，然后弃置 %src 的两张牌",
	["jl_sstj"] = "杀闪桃酒",
	[":jl_sstj"] = "基本牌<br /><b>卡牌效果</b>：此牌可视为【杀】、【闪】、【桃】、【酒】使用或打出。",
	["jl_bajun"] = "八骏",
	[":jl_bajun"] = "装备牌·坐骑<br /><b>装备效果</b>：装备【八骏】时，弃置装备区里的其它牌；卸载【八骏】时，可以从其他角色装备区里获得任意张牌。<br />锁定技。你计算与其他角色的距离-8；其他角色计算与你的距离+8",
	["@jl_bajun"] = "八骏：请选择能够获得装备",
	["jl_bingyuegong"] = "冰月弓",
	[":jl_bingyuegong"] = "装备牌·武器<br /><b>装备效果</b>：锁定技。你于出牌阶段内使用【杀】无次数限制；你的【杀】无视目标的防具；你使用【杀】对没有手牌的目标造成伤害+1。<br />你可以将两张手牌当【杀】使用或打出；你使用【杀】为最后的手牌时，可以额外选择至多两名目标；你可以将一张普通【杀】当火【杀】使用；当你指定异性角色为【杀】的目标后，你可以令其选择一项：弃置一张手牌，或令你摸一张牌；当你使用的【杀】被【闪】抵消后，你可以弃置两张牌令此【杀】继续造成伤害，或对该角色再使用一张【杀】（无距离限制且不能选择额外目标）；每当你使用【杀】对目标角色造成伤害时，你可以弃置其装备区内的一张坐骑牌；每当你使用【杀】对目标角色造成伤害时，若该角色有牌，你可以防止此伤害，然后依次弃置其两张牌。你的回合外，每当你使用或打出了一张黑色牌时，你可以使用一张【杀】",
	["@guanbing"] = "%src：你可以弃置两张牌令此 %dest 依然命中",
	["@bingyuegong-slash"] = "你可以立即再对 %src 使用一张【杀】",
	["jl_bingyuegong:choice1"] = "你可以发动“冰月弓”令 %src 选择弃一张牌或令你摸一张牌",
	["jl_bingyuegong:choice2"] = "你可以发动“冰月弓”令此 【%src】 转化为【火杀】",
	["jl_bingyuegong:choice3"] = "你可以发动“冰月弓”弃置 %src 的坐骑牌",
	["jl_bingyuegong:choice4"] = "你可以发动“冰月弓”防止此伤害，然后弃置 %src 的两张牌",
	["jl_yushanss"] = "羽扇双蛇刀",
	[":jl_yushanss"] = "装备牌·武器<br /><b>装备效果</b>：你可以将两张手牌当【杀】使用或打出；你可以将一张普通【杀】当火【杀】使用；每当你指定异性角色为【杀】的目标后，你可以令其选择一项：弃置一张手牌，或令你摸一张牌；每当你使用的【杀】被【闪】抵消后，你可以对该角色再使用一张【杀】（无距离限制且不能选择额外目标）；",
	["jl_yushanss:choice2"] = "你可以发动“羽扇双蛇刀”令此 【%src】 转化为【火杀】",
	["jl_yushanss:choice1"] = "你可以发动“羽扇双蛇刀”令 %src 选择弃一张牌或令你摸一张牌",
	["jl_yanlinmao"] = "Cổ Gia Cát Yển Công Kỳ Lân Họa Băng Thạch Vũ Mâu",--偃麟矛
	[":jl_yanlinmao"] = "Bài Trang Bị - Vũ khí\n\n<b>Tầm đánh</b>: 5\n<b>Kỹ năng</b>:\n* Bạn không giới hạn số lần sử dụng lá [Sát];\n* Sau khi xác định mục tiêu của lá [Sát], vô hiệu hoá phòng cụ của mục tiêu;* Khi bạn gây sát thương cho mục tiêu của lá [Sát], nếu mục tiêu không có bài trên tay, bạn lệnh sát thương này +1;\n* Bạn có thể chuyển hóa sử dụng/đánh ra 2 lá trên tay thành [Sát];\n* Nếu lá [Sát] bạn sử dụng là lá cuối cùng trên tay, bạn có thể chỉ định thêm 2 mục tiêu cho [Sát] này;\n* Khi bạn sử dụng [Sát] phổ thông, bạn có thể biến [Sát] này thành [Sát Hỏa];\n* Sau khi xác định từng mục tiêu của [Sát], nếu mục tiêu khác giới tính với bạn, bạn có thể lệnh mục tiêu chọn bỏ 1 lá bài trên tay hoặc lệnh bạn rút 1 lá bài;\n* Sau khi [Sát] bạn sử dụng bị triệt tiêu bởi [Thiểm] của mục tiêu, bạn có thể chọn sử dụng 1 [Sát] khác với mục tiêu (Không giới hạn khoảng cách và không thể chọn thêm mục tiêu) hoặc bỏ 2 lá, lệnh cho [Sát] này vẫn có hiệu quả đối với mục tiêu này;\n* Khi bạn gây sát thương cho mục tiêu của [Sát], bạn có thể bỏ 1 Ngựa trong vùng trang bị của mục tiêu;\n* Khi bạn gây sát thương cho mục tiêu của [Sát], nếu mục tiêu có bài, bạn có thể chặn sát thương này lại và lần lượt bỏ 2 lá của mục tiêu.",
	["jl_yanlinmao:choice1"] = "你可以发动“古诸葛偃釭麒麟画冰石羽矛”令 %src 选择弃一张牌或令你摸一张牌",
	["jl_yanlinmao:choice2"] = "你可以发动“古诸葛偃釭麒麟画冰石羽矛”令此 【%src】 转化为【火杀】",
	["jl_yanlinmao:choice3"] = "你可以发动“古诸葛偃釭麒麟画冰石羽矛”弃置 %src 的坐骑牌",
	["jl_yanlinmao:choice4"] = "你可以发动“古诸葛偃釭麒麟画冰石羽矛”防止此伤害，然后弃置 %src 的两张牌",
	["#bajuncard"] = "其他角色装备",
	["jl_liushen"] = "陆神",
	[":jl_liushen"] = "装备牌·防具<br /><b>装备效果</b>：若你的武将牌为关羽，吕布，吕蒙，诸葛亮，曹操，周瑜，装备后变为对应神武将牌",
	["jl_wanxiangqq"] = "万象齐侵",
	[":jl_wanxiangqq"] = "锦囊牌·AOE锦囊<br /><b>卡牌效果</b>：出牌阶段，对所有其他角色使用<br />目标需打出【杀】和【闪】，否则受到1点伤害。",
	["@jl_wanxiangqq"] = "万象齐侵：请打出一张 %src ，否则将受到1点伤害",
	["jl_lebucq"] = "乐不拆桥",
	[":jl_lebucq"] = "锦囊牌·延时锦囊<br /><b>卡牌效果</b>：出牌阶段，对一名判定区没有【乐不拆桥】的其他角色使用。将此牌置于目标判定区，然后弃置其一张牌；其判定阶段进行判定，若结果不为♥，其跳过此回合的出牌阶段。",
	["jl_shunshoubl"] = "顺手兵粮",
	[":jl_shunshoubl"] = "锦囊牌·延时锦囊<br /><b>卡牌效果</b>：出牌阶段，对一名与你距离为1且判定区没有【顺手兵粮】的其他角色使用。将此牌置于目标判定区，然后获得其一张牌；其判定阶段进行判定，若结果不为♣，其跳过此回合的摸牌阶段。",
	["jl_taoyuanfd"] = "桃园丰登",
	[":jl_taoyuanfd"] = "锦囊牌·全局锦囊<br /><b>卡牌效果</b>：出牌阶段，对所有角色使用。展示牌堆顶等于目标数的牌，则每名已受伤的目标回复1点体力并选择其中一张获得之，然后其余的牌置入弃牌堆。",
	["jl_huodou"] = "火斗",
	[":jl_huodou"] = "锦囊牌·单目标锦囊<br /><b>卡牌效果</b>：出牌阶段，对一名其他角色使用。目标需打出一张【杀】，然后你需弃置一张与此【杀】花色相同的手牌并重复此流程，直至一方未能执行，然后未能执行的角色受到1点火焰伤害。",
	["jlhuodou1"] = "火斗：请打出一张【杀】，否则将受到1点火焰伤害",
	["jlhuodou2"] = "火斗：请弃置一张与此【杀】花色相同的手牌，否则将受到1点火焰伤害",
	["jl_wuxiesy"] = "无懈生有",
	[":jl_wuxiesy"] = "锦囊牌·被动锦囊<br /><b>卡牌效果</b>：出牌阶段，对你使用。若【无懈生有】被抵消对目标的效果，目标摸两张牌。<br />当一张锦囊牌生效时，你可以使用【无懈生有】抵消其效果，然后摸两张牌。",
	["jl_qiefudao"] = "切腹刀",
	[":jl_qiefudao"] = "装备牌·武器<br /><b>装备效果</b>：你使用【杀】的目标只能指定自己。<br />注：装备后点击武器使用",
	["@jl_bingyuegong"] = "%src:你可以使用一张【杀】",
	["@bingyueg"] = "%src：你可以弃置一张手牌，否则 %dest 将摸一张牌",
	["jl_wuzijiang"] = "五子良将",
--	["&jl_wuzijiang"] = "颌辽禁进晃",
	["#jl_wuzijiang"] = "魏之壁垒",
	["designer:jl_wuzijiang"] = "lua学生",
	["illustrator:jl_wuzijiang"] = "lua学生",
	["jl_lianhuansr"] = "连环杀人",
	[":jl_lianhuansr"] = "锦囊牌·单目标锦囊<br /><b>卡牌效果</b>：出牌阶段，对一名有武器的其他角色使用。选择目标攻击范围内的一名角色，横置这两名角色，然后目标需对选择的角色使用一张【杀】，否则你获得目标装备区的武器牌。",
	["jl_dianshan"] = "电闪",
	[":jl_dianshan"] = "锦囊牌·延时锦囊<br /><b>卡牌效果</b>：当【电闪】不为从延时锦囊区置入弃牌堆时，将之置于此回合角色判定区。判定阶段时进行一次判定，若结果不为♠，其受到1点雷电伤害；判定结束后将【电闪】移至上家判定区。",
	["jl_beiju"] = "杯具",
	[":jl_beiju"] = "装备牌·宝物<br /><b>装备效果</b>：锁定技。当【杯具】移出装备区时，此回合角色失去X点体力（X为其体力值且至多为2）；当你受到伤害后，若此伤害大于1，你弃置【杯具】。",
	["@jl_hongfa-card"] = "请使用已选择的基本牌【%src】",
	["jl_shusixiang"] = "蜀汉四相",
--	["&jl_shusixiang"] = "亮琬允祎",
	["#jl_shusixiang"] = "竭忠尽智",
	["designer:jl_shusixiang"] = "lua学生",
	["illustrator:jl_shusixiang"] = "lua学生",
	["jl_guancheng"] = "观城",
	[":jl_guancheng"] = "你可以发动技能“观星”；若你没有手牌，你不能成为【杀】或【决斗】的目标。",
	["jl_zhencui"] = "镇瘁",
	[":jl_zhencui"] = "你可以发动技能“镇庭”和“尽瘁”（限一次）。",
	["jl_bingyan"] = "秉宴",
	[":jl_bingyan"] = "你可以发动技能“秉正”和“舍宴”。",
	["jl_jianxi"] = "谏息",
	[":jl_jianxi"] = "你可以发动技能“谏喻”和“生息”。",
	["jl_jianyu"] = "谏喻",
	["jl_jincui"] = "尽瘁",
	["mobileyanzhenting:zhenting0"] = "镇庭：你可以将此【%arg】的目标由 %src 转移给你",
	["zhenting1:zhenting2"] = "镇庭：你可以摸一张牌，否则弃置 %src 一张手牌",
	["$jl_wuxiesy0"] = "%arg 抵消了 %arg2 对 %to 的效果",
	["  "] = "  ",
	["from"] = "来源",
	["to"] = "目标",
	["  "] = "  ",
	["jl_sicai"] = "四才",
--	["&jl_sicai"] = "亮统徽庶",
	["#jl_sicai"] = "成名于世",
	["designer:jl_sicai"] = "lua学生",
	["illustrator:jl_sicai"] = "lua学生",
	["jl_wolong"] = "卧龙",
	[":jl_wolong"] = "你可以发动技能“八阵”、“火计”和“看破”。",
	["jl_fengcu"] = "凤雏",
	[":jl_fengcu"] = "你可以发动技能“连环”和“涅槃”（限一次）。",
	["jl_shuijing"] = "水镜",
	[":jl_shuijing"] = "你可以发动技能“称好”和“隐士”。",
	["jl_xuanjian"] = "玄剑",
	[":jl_xuanjian"] = "你可以发动技能“诛害”和“荐言”。",
	["@xuanjian"] = "%src 此回合造成了伤害，你可以对其使用一张【杀】",
	["jl_jianyan"] = "荐言",
	["@jianyan"] = "请选择一名男性角色获得此 %src",
	["jl_simahuini"] = "司马徽-逆",
	["&jl_simahuini"] = "司马徽",
	["#jl_simahuini"] = "神经先生",
	["designer:jl_simahuini"] = "lua学生",
	["illustrator:jl_simahuini"] = "lua学生",
	["jl_jianjie"] = "荐劫",
	[":jl_jianjie"] = "准备阶段，若场上没有“聋印”和“疯印”，你可以令两名角色各获得“聋印”和“疯印”,否则你可以转移“聋印”或“疯印”；拥有“聋印”/“疯印”的角色拥有“止息”/“无谋”，同时拥有“聋印”和“疯印”的角色拥有“崩坏”。",
	["jl_chencha"] = "称差",
	[":jl_chencha"] = "当一名角色使用一张伤害类牌后，若此牌未造成伤害，你可以令其失去1点体力。",
	["jl_yinshi"] = "淫士",
	[":jl_yinshi"] = "锁定技。你受到的同性角色伤害-1，异性角色伤害+1；你对同性角色造成的伤害+1，异性角色伤害-1",
	["jl_longyin"] = "聋印",
	["jl_fengyin"] = "疯印",
	["#jl_jianjie"] = "请选择令一名角色获得“%src”",
	["@jl_jianjie"] = "你可以分配或转移“聋印”*“疯印”",
	["jl_liuzhang"] = "刘璋",
--	["&jl_liuzhang"] = "刘璋",
	["#jl_liuzhang"] = "青出于蓝",
	["designer:jl_liuzhang"] = "lua学生",
	["illustrator:jl_liuzhang"] = "lua学生",
	["jl_fuhun"] = "父魂",
	[":jl_fuhun"] = "限定技。准备阶段你可以将武将牌替换为“刘焉”。",
	["jl_jutu"] = "据矛",
	[":jl_jutu"] = "回合开始时，你从牌堆或弃牌堆中获得并使用【丈八蛇矛】。",
	["jl_jugong"] = "沮宫",
--	["&jl_jugong"] = "沮宫",
	["#jl_jugong"] = "破防了",
	["designer:jl_jugong"] = "lua学生",
	["illustrator:jl_jugong"] = "lua学生",
	["jl_zhangjiao"] = "张餃",
--	["&jl_zhangjiao"] = "张角",
	["designer:jl_zhangjiao"] = "lua学生",
	["illustrator:jl_zhangjiao"] = "",
	["#jl_zhangjiao"] = "甜供酱菌",
	["jl_leiji"] = "泪击",
	[":jl_leiji"] = "当你指定或成为【杀】的目标后，你可以进行判定，若为♥，你可以令一名角色回复2点体力。",
	["jl_leiji0"] = "泪击：你可以选择令一名角色回复2点体力",
	["jl_guidao"] = "闺道",
	[":jl_guidao"] = "当一张判定牌生效前，你可以打出一张红色牌替换之。",
	["jl_guidao0"] = "闺道：你可以打出一张红色牌替换此判定牌",
	["jl_huangdian"] = "凰天",
	[":jl_huangdian"] = "<b>公主技</b>。其他男性角色出牌阶段限一次，其可以交给你一张【杀】。",
	["jl_huangdianvs"] = "凰天",
	[":jl_huangdianvs"] = "<b>公主技</b>。男性角色出牌阶段限一次，你可以交给“凰天”角色一张【杀】。",
	["jl_sunbb"] = "笨笨",
	["#jl_sunbb"] = "自欠毒打",
	["designer:jl_sunbb"] = "lua学生",
	["illustrator:jl_sunbb"] = "",
	["jl_jiang"] = "激昂",
	[":jl_jiang"] = "当你指定或成为【决斗】或红色【杀】的目标后，你可以摸一张牌，则此牌结算后，你可以将一张同花色手牌当作对应牌名的牌再对对方使用之。",
	["jl_yingzi"] = "英姿",
	[":jl_yingzi"] = "摸牌阶段，你可以额外摸一张牌，然后再次执行前面的效果。 ",
	["jl_yinghun"] = "英魂",
	[":jl_yinghun"] = "准备阶段开始时，你可以令一名其他角色将手牌摸至X或弃至X。（X为你已损失的体力）",
	["jl_jianzheng"] = "谏征",
	[":jl_jianzheng"] = "当其他角色使用红色【杀】指定目标时，若你不是目标，你可以将一张手牌置于牌堆顶，然后将目标改为你。",
	["jl_jiang0"] = "激昂：你可以将一张 %dest 手牌当作【%src】再对对方使用",
	["jl_yinghun0"] = "英魂：你可以令一名其他角色将手牌摸至 %src 或弃至 %src ",
	["jl_yinghun:jl_yinghun1"] = "英魂：你将令 %src 将手牌摸至 %dest 张，否则 %src 将手牌弃至 %dest 张",
	["jl_jianzheng0"] = "你可以将一张手牌置于牌堆顶，然后将此【%src】的目标改为你。",
	["  "] = "  ",
	["  "] = "  ",
	["@jl_leidaocard"] = "你可以打出一张黑色牌替换 %src 的判定牌",
	["jl_leidaoinvoke"] = "你可以选择一名角色进行判定，若为黑桃，其受到2点雷电伤害",
	["@jl_lianhuansr"] = "请对 %src 使用一张【杀】，否则 %dest 将获得你的武器",
	["@jl_guikui-card"] = "你可以打出一张手牌代替 %src 的判定牌",
	["jl_lvmeng"] = "吕蒙",
--	["&jl_lvmeng"] = "吕蒙",
	["#jl_lvmeng"] = "恐惧魔王",
	["designer:jl_lvmeng"] = "lua学生",
	["illustrator:jl_lvmeng"] = "lua学生",
	["jl_weihe"] = "威吓",
	[":jl_weihe"] = "一名其他“恐惧”角色死亡时，你摸X张牌（X为其拥有的“恐惧”标记数）；若你的手牌数不小于100，你的“后期”视为满足条件。",
	["jl_kongju"] = "恐惧",
	["jl_keji"] = "克己",
	[":jl_keji"] = "出牌阶段结束后，若你未于此阶段使用或打出过【杀】，你可以跳过弃牌阶段，然后令场上所有其他角色各获得1枚“恐惧”标记。",
	["jl_houqi"] = "后期",
	[":jl_houqi"] = "觉醒技。当场上的“恐惧”标记数不小于100时，你获得游戏胜利。",
	["jl_caoang"] = "曹昂",
--	["&jl_caoang"] = "曹昂",
	["#jl_caoang"] = "犯大吴疆土者",
	["designer:jl_caoang"] = "lua学生",
	["illustrator:jl_caoang"] = "",
	["jl_yangguang"] = "阳光",
	[":jl_yangguang"] = "当一名角色成为【杀】的目标后，你可以从摸牌堆或弃牌堆中随机获得一张【闪】，则你可以交给其一张牌，然后其可以使用【闪】抵消此【杀】的伤害。",
	["@jl_yangguang"] = "阳光：你可以交给 %src 一张牌",
	["@jl_yangguang1"] = "阳光：你可以使用【闪】抵消此【%src】的伤害",
	["jl_zhenggong"] = "争功",
	[":jl_zhenggong"] = "一名其他角色回合开始前，若你正面朝上，你可以执行一个额外回合，此额外回合结束后你翻面。",
	["jl_sanyinxiang"] = "三音响",
--	["&jl_sanyinxiang"] = "衡攸赞",
	["#jl_sanyinxiang"] = "吵死你",
	["designer:jl_sanyinxiang"] = "lua学生",
	["illustrator:jl_sanyinxiang"] = "",
	["jl_kuangcai"] = "狂才",
	[":jl_kuangcai"] = "出牌阶段开始时，你可以令你此阶段使用牌无次数与距离限制，且使用时摸一张牌；累计摸5张后结束此阶段。",
	["$jl_kuangcai1"] = "博古揽今，信手拈来。",
	["$jl_kuangcai2"] = "功名为尘，光阴为金。",
	["jl_yuanyan"] = "袁焉",
--	["&jl_yuanyan"] = "袁焉",
	["#jl_yuanyan"] = "高贵之宗",
	["designer:jl_yuanyan"] = "",
	["illustrator:jl_yuanyan"] = "lua学生",
	["jl_jiangj"] = "姜姜",
--	["&jl_jiangj"] = "姜姜",
	["#jl_jiangj"] = "生气了",
	["designer:jl_jiangj"] = "lua学生",
	["illustrator:jl_jiangj"] = "",
	["jl_kunfen"] = "坤愤",
	[":jl_kunfen"] = "出牌阶段，你可以弃置两张牌对一名角色造成1点伤害。",
	["jl_fengliang"] = "缝靓",
	[":jl_fengliang"] = "限定技。回合结束时，若你此回合累计造成的伤害大于你的体力，你可以扣减1点体力上限并回复1点体力，然后令一名角色获得“吊屑”。",
	["jl_diaoxie"] = "吊屑",
	[":jl_diaoxie"] = "锁定技。其他角色使用的单目标伤害类牌只能指定你为目标（无视距离）。",
	["#jl_fengliang"] = "缝靓：请选择令一名角色获得“%src”",
	["jl_gouhuo"] = "苟或",
	["#jl_gouhuo"] = "阅读理解",
	["designer:jl_gouhuo"] = "沃矢逆蝶",
	["illustrator:jl_gouhuo"] = "沃矢逆蝶",
	["jl_yedu"] = "阅读",
	[":jl_yedu"] = "出牌阶段限一次。你可以令一名其他角色摸一张牌，然后与其拼点；根据以下结果执行对应效果：1.若你赢且未对去发动过“阅读”，其选择一项："..
	"弃一张牌并失去1点体力且本回合你可以额外使用一张【杀】，或翻面并与你摸等同于自己已损失的体力值的牌，然后你可以弃置一张牌，失去1点体力，额外发动一"..
	"次此技能并将手牌补至体力上限；2.若你没赢且未对其发动过“阅读”，其选择一项：翻面并摸等同于自己已损失的体力值的牌，或将一张♣或♦置于自己判定区，♣视为"..
	"【兵粮寸断】♦视为【乐不思蜀】并回复1点体力，然后你可以翻面，将一张手牌当作【铁索连环】对你使用，并再次发动此技能且本回合手牌上限+1；3.若你赢且对其"..
	"发动过“阅读”，则你选择一项：对其造成1点伤害你与其各摸一张牌，然后其中手牌少的获得手牌多的角色一张手牌并展示之，然后根据类型执行对应效果：基本牌，使"..
	"用之或失去1点体力，锦囊牌，交给对方一张锦囊或弃置两张非锦囊，装备牌，使用之并失去1点体力；或者获得其区域内所有的牌，然后本回合结束按照每个装备栏，判"..
	"定区,体力，各分配给其一张手牌；4.若你没赢且对其发动过“阅读”，则其选择一项：交给你其区域内各一张牌，然后本回合你不能再对其他角色使用牌，且其下回合黑色"..
	"手牌不计入上限直到回合结束，或者令你获得双方拼点牌，交给你一张牌并失去1点体力，你立即结束出牌阶段且本回合手牌上限-1，并且其下回合获得的牌在回合内不计入"..
	"手牌上限。一切结算完成后，双方根据拼点牌执行以下效果：♠，失去1点体力，摸一张牌；♥，回复1点体力，弃置一张牌；♣，弃置两张牌，执行一个额外回合，♦，摸两张牌"..
	"并翻面。最后你选择一项：令其横置并摸一张牌；弃置其3张牌并令其摸两张牌；对其造成1点伤害并令其摸3张牌；获得其所有手牌并令其摸4张牌。然后若你的手牌数大于5，"..
	"则你选择：将手牌数弃到5或失去体力值至1；若你的手牌数小于5，则你选择：将手牌数补至5或回复体力至上限。",
	["jl_lijie"] = "理解",
	[":jl_lijie"] = "游戏开始时，如果你实在看不懂“阅读”技能说明，你可以将武将牌替换为“荀彧”进行游戏。",
	["@jl_yedu"] = "你可以弃置一张牌并失去1点体力，否则你翻面并摸等同于已损失体力数的牌",
	["@jl_yedu1"] = "你可以弃置一张牌，失去1点体力，额外发动一次此技能并将手牌补至体力上限",
	["@jl_yedu2"] = "你选择：翻面并摸等同于自己已损失的体力值的牌，或将一张♣或♦置于自己判定区，♣视为【兵粮寸断】♦视为【乐不思蜀】并回复1点体力",
	["@jl_yedu3"] = "请选择将一张手牌当作【铁索连环】对你使用",
	["@jl_yedu4"] = "请再次发动 %src",
	["@jl_yedu5"] = "请使用【%src】，否则失去1点体力",
	["@jl_yedu6"] = "请选择一张锦囊交给 %src ，否则弃置两张非锦囊",
	["@jl_yedu7"] = "请选择弃置两张非锦囊",
	["@jl_yedu8"] = "请交给 %src 你区域内各一张牌，否则 %src 获得双方拼点牌",
	["@jl_yedu9"] = "请交给 %src 一张手牌",
	["@jl_yedu10"] = "请弃置 %src 张牌，否则将失去体力值至1点",
	["jl_yeduchoice1"] = "对其造成1点伤害你与其各摸一张牌",
	["jl_yeduchoice2"] = "获得其区域内所有的牌",
	["jl_yeduchoice3"] = "令其横置并摸一张牌",
	["jl_yeduchoice4"] = "弃置其3张牌并令其摸两张牌",
	["jl_yeduchoice5"] = "对其造成1点伤害并令其摸3张牌",
	["jl_yeduchoice6"] = "获得其所有手牌并令其摸4张牌",
	["jl_yeduchoice7"] = "将手牌数补至5张",
	["jl_yeduchoice8"] = "回复体力至上限",
	["jl_lijie:@jl_lijie"] = "理解：若你未看懂“阅读”技能说明，你可以将武将牌替换为“荀彧”",
	["jl_sunben"] = "孙笨",
	["#jl_sunben"] = "作文之王",
	["designer:jl_sunben"] = "",
	["illustrator:jl_sunben"] = "",
	["jl_yedus"] = "阅读",
	[":jl_yedus"] = "限定技。出牌阶段，你可以令所有角色依次弃置一张牌，然后你可以令此牌点数+X/-X，且该角色可以猜测其下家弃置的牌类别是否和他相同（不公布），若猜对："..
	"其摸一张牌；猜错，其下家获得“蛊惑”且其获得“缠怨”直到回合结束。若其以此法弃置的牌是基本牌，其可以将之置于牌堆顶，然后从牌堆底摸一张牌；若为锦囊牌，则该角色可以把"..
	"此牌当作【杀】使用，然后将此牌交给此【杀】目标；若为装备牌，则其选择交给你或置于牌堆顶。然后比较其弃置的牌的点数和其上家弃置的牌的点数，若比其上家点数大，则该角色"..
	"需选择1项：1.交给你一张牌，若此牌为装备牌或延时锦囊牌，则你可以使用之，若此牌为基本牌或普通锦囊牌，则该角色视为使用之；以此法使用或打出的牌结算完毕后，若此牌目标"..
	"角色是此技能目标且尚未因此技能弃牌，则令其获得1枚“复”标记；2.失去1点体力，然后若其体力值与手牌数之和不小于其弃置的牌的点数，你令其获得1枚“复”标记。若比其上家点数"..
	"小：你令其摸一张牌并展示之，若此牌与其弃置的牌花色相同，你摸两张牌或弃置其两张牌，否则你令其获得1枚“复”标记；此技能结算完成后，你摸X张牌，然后若你的手牌数不大于其"..
	"他角色手牌数之和，你令所有拥有“复”标记的角色移去1枚“复”标记，然后你以这些角色为目标再次发动此技能；若你的手牌数大于其他所有角色手牌数之和，你令所有角色弃置区域1内"..
	"所有的牌,然后亮出牌堆顶X张牌，并令所有角色依次获得其中一张；若这些牌没有被玩家全部获得，你依次使用其中任意张，将其余牌置于弃牌堆或牌堆顶。若有角色于此技能结算过程"..
	"中体力值归零，则其先不进行濒死结算，让这些角色先以体力值为0的状态继续游戏，在此技能结算完成后再依次结算这些角色的濒死状态。（X为场上的“复”标记数量）",
	["jl_lijies"] = "理解",
	[":jl_lijies"] = "游戏开始时，如果你实在看不懂“阅读”技能说明，你可以将武将牌替换为“孙策”进行游戏。",
	["jl_yedus0"] = "阅读：请弃置一张牌",
	["jl_yedus:jl_yedus1"] = "阅读：令此牌点数+%src",
	["jl_yedus:jl_yedus2"] = "阅读：令此牌点数-%src",
	["jl_yedus3"] = "阅读：猜测你弃置的牌与下家弃置的相同",
	["jl_yedus4"] = "阅读：猜测你弃置的牌与下家弃置的不同",
	["jl_yeduscard:jl_yedus5"] = "阅读：你可以将此 %src 置于牌堆顶，否则 %dest 获得之",
	["jl_yedus6"] = "阅读：你可以将 %src 当作【杀】使用",
	["jl_yeduscard:jl_yedus7"] = "阅读：你可以将此 %src 置于牌堆顶，然后从牌堆底摸一张牌",
	["jl_yedus8"] = "阅读：你可以交给 %src 一张牌，否则失去1点体力",
	["jl_yedus9"] = "阅读：你可以使用此 %src ",
	["jl_yedus10"] = "阅读：你可以视为使用 %src ",
	["jl_yeduscard:jl_yedus11"] = "阅读：你可以摸两张牌，否则弃置 %src 两张牌",
	["jl_yedus12"] = "阅读：请选择一张牌使用之",
	["jl_yedus13"] = "阅读：你可以将这些牌置于牌堆顶，否则置入弃牌堆",
	["jl_lijies:@jl_lijies"] = "理解：如果你实在看不懂“阅读”技能说明，你可以将武将牌替换为“孙策”进行游戏",
	["jl_fus"] = "复",
	["AskUseCard"] = "出牌",
	["jl_shengsheng"] = "盛盛",
	["#jl_shengsheng"] = "江东的爹地",
	["designer:jl_shengsheng"] = "lua学生",
	["illustrator:jl_shengsheng"] = "",
	["jl_pojun"] = "破君",
	[":jl_pojun"] = "锁定技。你使用伤害类牌指定唯一目标后，你获得其所有牌，然后此牌结算后，你按其体力值交给其等量的牌；你对没有牌的角色造成的伤害+1。",
	["$jl_pojun1"] = "犯吾疆土者，盛盛必鸡儿破之",
	["$jl_pojun2"] = "若敢来饭，盛盛必叫你大饱而归",
	["jl_caodun"] = "曹吨",
	["#jl_caodun"] = "唬抱稽手",
	["designer:jl_caodun"] = "lua学生",
	["illustrator:jl_caodun"] = "",
	["jl_shanjia"] = "善假",
	[":jl_shanjia"] = "出牌阶段开始时，你弃置所有牌，然后摸双倍的牌；若你弃置的牌数大于场上其他角色数，你视为对所有其他角色使用一张【杀】（不计次数且无距离限制）。",
	["jl_luxun"] = "陆逊",
	["#jl_luxun"] = "辱生凶才",
	["designer:jl_luxun"] = "lua学生",
	["illustrator:jl_luxun"] = "",
	["jl_qianxun"] = "纤逊",
	[":jl_qianxun"] = "锁定技。当你成为【乐不思蜀】或【顺手牵羊】的目标时，你变换来源与目标。",
	["jl_lianying"] = "连赢",
	[":jl_lianying"] = "当你于回合内/回合外失去最后一张手牌后，你可以随机摸一张可以主动/被动使用的牌。",
	["jl_sunce"] = "孙策",
	["#jl_sunce"] = "江东小白板",
	["designer:jl_sunce"] = "lua学生",
	["illustrator:jl_sunce"] = "杜总",
	["jl_baiban"] = "白板",
	[":jl_baiban"] = "锁定技。防止你跳过阶段；防止你翻面；防止你横置；你的摸牌数始终为2；你拥有此技能时失去所有其他技能；你失去此技能时恢复所有以此法失去的技能。",
	["jl_caojinyu"] = "草金鱼",
	["#jl_caojinyu"] = "阴间制裁",
	["designer:jl_caojinyu"] = "lua学生",
	["illustrator:jl_caojinyu"] = "",
	["jl_jinghun"] = "惊魂",
	[":jl_jinghun"] = "当你距离[1]以内的角色造成伤害时，你可以观看牌堆顶[1]张牌，则你分配给其至少[1]张牌，分配给你至多[1]张牌，然后伤害改为目标失去1点体力并将剩余的牌置回牌堆顶",
	[":jl_jinghun2"] = "当你距离[%arg1]以内的角色造成伤害时，你可以观看牌堆顶[%arg2]张牌，则你分配给其至少[%arg3]张牌，分配给你至多[%arg4]张牌，然后伤害改为目标失去1点体力并将剩余的牌置回牌堆顶",
	["jl_guiying"] = "鬼影",
	[":jl_guiying"] = "准备阶段或一名角色濒死时，你可以令“惊魂”[ ]中的一个数字+1（数字至多为5）；若你已受伤，你再次执行前面的效果。",
	["jl_jinghun_1"] = "距离以内+1",
	["jl_jinghun_2"] = "观看牌堆顶牌+1",
	["jl_jinghun_3"] = "分配给其至少牌+1",
	["jl_jinghun_4"] = "分配给你至多牌+1",
	["#jinghuncard"] = "惊魂观看牌堆",
	["jl_jinghun0"] = "惊魂：请将至少 %dest 张观看牌交给 %src",
	["jl_jinghun1"] = "惊魂：请将至多 %dest 张观看牌交给 %src",
	["jl_sangg"] = "三公公",
--	["&jl_sangg"] = "让昏皓",
	["#jl_sangg"] = "乱朝三公",
	["designer:jl_sangg"] = "lua学生",
	["illustrator:jl_sangg"] = "lua学生",
	["jl_shehuo"] = "奢祸",
	[":jl_shehuo"] = "你可以发动“极奢”且会触发“链祸”。",
	["jl_huiqing"] = "贿情",
	[":jl_huiqing"] = "你可以发动“寝情”和“贿生”。",
	["jl_siyishou"] = "四夷首",
--	["&jl_siyishou"] = "获居吉顿",
	["#jl_siyishou"] = "四方扰壤",
	["designer:jl_siyishou"] = "lua学生",
	["illustrator:jl_siyishou"] = "lua学生",
	["jl_huoqi"] = "祸起",
	[":jl_huoqi"] = "你可以发动“再起”且会触发“祸首”",
	["jl_qiangxuan"] = "羌悬",
	[":jl_qiangxuan"] = "你可以发动“车悬”且会触发“羌首”",
	["jl_kouren"] = "寇认",
	[":jl_kouren"] = "你可以发动“寇略”和“随认”",
	["jl_chaiqiandui"] = "拆迁队",
	["#jl_chaiqiandui"] = "扒光你",
	["designer:jl_chaiqiandui"] = "lua学生",
	["illustrator:jl_chaiqiandui"] = "lua学生",
	["jl_chaixie"] = "拆卸",
	[":jl_chaixie"] = "你可以发动以下技能：<br />“奇袭”、“英魂”、“归心”、“突袭”、“刚烈”、“急袭”、“趫猛”、“挑衅”、“反馈”和“猛进”；然后将以此法弃置的牌当作“田”置于武将牌上。",
	["jl_shuapaiji"] = "刷牌姬",
--	["&jl_shuapaiji"] = "英华香逊",
	["#jl_shuapaiji"] = "信仰之力",
	["designer:jl_shuapaiji"] = "lua学生",
	["illustrator:jl_shuapaiji"] = "lua学生",
	["jl_jixi"] = "急袭",
	["jl_baxianding"] = "八限定",
	["#jl_baxianding"] = "惊世之变",
	["designer:jl_baxianding"] = "lua学生",
	["illustrator:jl_baxianding"] = "lua学生",
	["jl_xianfa"] = "限发",
	[":jl_xianfa"] = "你可以发动以下技能：<br />“雄异”、“间书”、“拥嫡”、“伏枥”、“焚城”、“焚心”、“乱武”、“涅槃”。（每个技能限一次）",
	["jl_xianfa0"] = "限发:你可以发动“%src”",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
	["  "] = "  ",
}

return {extensioncard}